// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7
// Source: project-management.proto

package projectmanagementservice

import (
	"context"

	"explorapal/app/project-management/rpc/projectmanagement"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateProjectReq        = projectmanagement.CreateProjectReq
	CreateProjectResp       = projectmanagement.CreateProjectResp
	ExpressionInfo          = projectmanagement.ExpressionInfo
	GetProjectDetailReq     = projectmanagement.GetProjectDetailReq
	GetProjectDetailResp    = projectmanagement.GetProjectDetailResp
	GetProjectListReq       = projectmanagement.GetProjectListReq
	GetProjectListResp      = projectmanagement.GetProjectListResp
	ObservationInfo         = projectmanagement.ObservationInfo
	ProjectAchievement      = projectmanagement.ProjectAchievement
	ProjectActivity         = projectmanagement.ProjectActivity
	ProjectDetail           = projectmanagement.ProjectDetail
	ProjectInfo             = projectmanagement.ProjectInfo
	QuestionInfo            = projectmanagement.QuestionInfo
	UpdateProjectStatusReq  = projectmanagement.UpdateProjectStatusReq
	UpdateProjectStatusResp = projectmanagement.UpdateProjectStatusResp

	ProjectManagementService interface {
		CreateProject(ctx context.Context, in *CreateProjectReq, opts ...grpc.CallOption) (*CreateProjectResp, error)
		GetProjectList(ctx context.Context, in *GetProjectListReq, opts ...grpc.CallOption) (*GetProjectListResp, error)
		GetProjectDetail(ctx context.Context, in *GetProjectDetailReq, opts ...grpc.CallOption) (*GetProjectDetailResp, error)
		UpdateProjectStatus(ctx context.Context, in *UpdateProjectStatusReq, opts ...grpc.CallOption) (*UpdateProjectStatusResp, error)
	}

	defaultProjectManagementService struct {
		cli zrpc.Client
	}
)

func NewProjectManagementService(cli zrpc.Client) ProjectManagementService {
	return &defaultProjectManagementService{
		cli: cli,
	}
}

func (m *defaultProjectManagementService) CreateProject(ctx context.Context, in *CreateProjectReq, opts ...grpc.CallOption) (*CreateProjectResp, error) {
	client := projectmanagement.NewProjectManagementServiceClient(m.cli.Conn())
	return client.CreateProject(ctx, in, opts...)
}

func (m *defaultProjectManagementService) GetProjectList(ctx context.Context, in *GetProjectListReq, opts ...grpc.CallOption) (*GetProjectListResp, error) {
	client := projectmanagement.NewProjectManagementServiceClient(m.cli.Conn())
	return client.GetProjectList(ctx, in, opts...)
}

func (m *defaultProjectManagementService) GetProjectDetail(ctx context.Context, in *GetProjectDetailReq, opts ...grpc.CallOption) (*GetProjectDetailResp, error) {
	client := projectmanagement.NewProjectManagementServiceClient(m.cli.Conn())
	return client.GetProjectDetail(ctx, in, opts...)
}

func (m *defaultProjectManagementService) UpdateProjectStatus(ctx context.Context, in *UpdateProjectStatusReq, opts ...grpc.CallOption) (*UpdateProjectStatusResp, error) {
	client := projectmanagement.NewProjectManagementServiceClient(m.cli.Conn())
	return client.UpdateProjectStatus(ctx, in, opts...)
}
