// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7

package types

type AIResponse struct {
	Answer     string   `json:"answer" desc:"AI回答"`
	KeyPoints  []string `json:"key_points" desc:"关键要点"`
	Examples   []string `json:"examples" desc:"举例说明"`
	Analogies  []string `json:"analogies" desc:"类比"`
	VisualAids []string `json:"visual_aids" desc:"视觉辅助建议"`
}

type ARHotspot struct {
	X       float64 `json:"x" desc:"X坐标(0-1)"`
	Y       float64 `json:"y" desc:"Y坐标(0-1)"`
	Title   string  `json:"title" desc:"热点标题"`
	Content string  `json:"content" desc:"热点内容"`
	Type    string  `json:"type" desc:"热点类型：feature,fact,question"`
}

type ARInformation struct {
	Hotspots []ARHotspot `json:"hotspots" desc:"AR热点"`
	Labels   []ARLabel   `json:"labels" desc:"AR标签"`
}

type ARLabel struct {
	X     float64 `json:"x" desc:"X坐标(0-1)"`
	Y     float64 `json:"y" desc:"Y坐标(0-1)"`
	Text  string  `json:"text" desc:"标签文本"`
	Color string  `json:"color" desc:"标签颜色"`
}

type Activity struct {
	Type        string   `json:"type" desc:"活动类型：experiment,drawing,comparison,roleplay"`
	Title       string   `json:"title" desc:"活动标题"`
	Description string   `json:"description" desc:"活动描述"`
	Materials   []string `json:"materials" desc:"所需材料"`
	Steps       []string `json:"steps" desc:"步骤说明"`
	Duration    int32    `json:"duration" desc:"预计时长(分钟)"`
	Difficulty  string   `json:"difficulty" desc:"难度"`
}

type AnalyzeVideoReq struct {
	ProjectId    int64   `json:"project_id" desc:"项目ID"`
	UserId       int64   `json:"user_id" desc:"用户ID"`
	VideoData    string  `json:"video_data" desc:"base64编码的视频数据"`
	VideoFormat  string  `json:"video_format" desc:"视频格式：mp4,avi,mov"`
	AnalysisType string  `json:"analysis_type,optional,default=content" desc:"分析类型：content,scene,object,emotion"`
	Duration     float64 `json:"duration,optional" desc:"分析时长(秒)，0表示分析整个视频"`
}

type AnalyzeVideoResp struct {
	VideoAnalysis VideoAnalysisResult `json:"video_analysis" desc:"视频分析结果"`
	AchievementId int64               `json:"achievement_id" desc:"成果ID"`
}

type AudioAnalysis struct {
	Timestamp     float64 `json:"timestamp" desc:"时间戳(秒)"`
	Transcription string  `json:"transcription" desc:"语音转文字"`
	Language      string  `json:"language" desc:"语言"`
	Confidence    float64 `json:"confidence" desc:"置信度"`
}

type BoundingBox struct {
	X      float64 `json:"x" desc:"左上角x坐标"`
	Y      float64 `json:"y" desc:"左上角y坐标"`
	Width  float64 `json:"width" desc:"宽度"`
	Height float64 `json:"height" desc:"高度"`
}

type ColorScheme struct {
	Primary   string   `json:"primary" desc:"主色"`
	Secondary string   `json:"secondary" desc:"辅色"`
	Accent    string   `json:"accent" desc:"强调色"`
	Palette   []string `json:"palette" desc:"调色板"`
}

type CommonStatusResp struct {
	Code    int32  `json:"code" desc:"响应码"`
	Message string `json:"message" desc:"响应消息"`
}

type ContextInfo struct {
	ObservationResults string `json:"observation_results,optional" desc:"观察结果"`
	PreviousAnswers    string `json:"previous_answers,optional" desc:"之前回答"`
	ProjectCategory    string `json:"project_category" desc:"项目类别"`
	UserAge            int32  `json:"user_age,optional" desc:"用户年龄"`
}

type CreateProjectReq struct {
	UserId      int64    `json:"user_id" desc:"用户ID"`
	Title       string   `json:"title" desc:"项目标题"`
	Description string   `json:"description,optional" desc:"项目描述"`
	Category    string   `json:"category" desc:"项目类别：dinosaur,rocket,minecraft等"`
	Tags        []string `json:"tags,optional" desc:"标签"`
}

type CreateProjectResp struct {
	ProjectId   int64  `json:"project_id" desc:"项目ID"`
	ProjectCode string `json:"project_code" desc:"项目编码"`
	Status      string `json:"status" desc:"项目状态"`
}

type DocumentaryScript struct {
	Title     string   `json:"title" desc:"纪录片标题"`
	Duration  int32    `json:"duration" desc:"预计时长(秒)"`
	Style     string   `json:"style" desc:"风格"`
	Scenes    []Scene  `json:"scenes" desc:"场景列表"`
	Narration string   `json:"narration" desc:"旁白脚本"`
	Music     string   `json:"music" desc:"背景音乐建议"`
	Effects   []string `json:"effects" desc:"音效建议"`
}

type EmotionAnalysis struct {
	Timestamp   float64 `json:"timestamp" desc:"时间戳(秒)"`
	Emotion     string  `json:"emotion" desc:"情感类型"`
	Confidence  float64 `json:"confidence" desc:"置信度"`
	Description string  `json:"description" desc:"情感描述"`
}

type ExpressionInfo struct {
	ExpressionId int64  `json:"expression_id" desc:"表达ID"`
	Content      string `json:"content" desc:"内容"`
	Type         string `json:"type" desc:"类型：speech,text,note"`
	PolishedNote string `json:"polished_note,optional" desc:"润色后的笔记"`
	CreateTime   string `json:"create_time" desc:"创建时间"`
}

type Finding struct {
	Title        string   `json:"title" desc:"发现标题"`
	Description  string   `json:"description" desc:"发现描述"`
	Evidence     []string `json:"evidence" desc:"证据"`
	Significance string   `json:"significance" desc:"重要性"`
}

type GenerateDocumentaryReq struct {
	ProjectId int64  `json:"project_id" desc:"项目ID"`
	UserId    int64  `json:"user_id" desc:"用户ID"`
	Style     string `json:"style,optional,default=narrative" desc:"纪录片风格：narrative,scientific,adventure"`
	Length    string `json:"length,optional,default=short" desc:"时长：short(1分钟),medium(3分钟),long(5分钟)"`
}

type GenerateDocumentaryResp struct {
	Documentary   DocumentaryScript `json:"documentary" desc:"纪录片脚本"`
	AchievementId int64             `json:"achievement_id" desc:"成果ID"`
	VideoUrl      string            `json:"video_url,optional" desc:"生成的视频URL"`
	AudioUrl      string            `json:"audio_url,optional" desc:"生成的音频URL"`
}

type GeneratePosterReq struct {
	ProjectId int64  `json:"project_id" desc:"项目ID"`
	UserId    int64  `json:"user_id" desc:"用户ID"`
	Style     string `json:"style,optional,default=scientific" desc:"海报风格：scientific,creative,educational"`
	Layout    string `json:"layout,optional,default=standard" desc:"布局：standard,creative,minimal"`
}

type GeneratePosterResp struct {
	Poster        PosterDesign `json:"poster" desc:"海报设计"`
	AchievementId int64        `json:"achievement_id" desc:"成果ID"`
	ImageUrl      string       `json:"image_url,optional" desc:"生成的图片URL"`
}

type GenerateQuestionsReq struct {
	ProjectId     int64  `json:"project_id" desc:"项目ID"`
	UserId        int64  `json:"user_id" desc:"用户ID"`
	ObservationId int64  `json:"observation_id" desc:"观察记录ID"`
	ContextInfo   string `json:"context_info" desc:"观察上下文信息"`
	Category      string `json:"category" desc:"项目类别"`
	UserAge       int32  `json:"user_age" desc:"用户年龄"`
}

type GenerateQuestionsResp struct {
	Questions []Question `json:"questions" desc:"生成的引导问题"`
}

type GenerateReportReq struct {
	ProjectId   int64  `json:"project_id" desc:"项目ID"`
	UserId      int64  `json:"user_id" desc:"用户ID"`
	ProjectData string `json:"project_data" desc:"项目数据"`
	Category    string `json:"category" desc:"项目类别"`
}

type GenerateReportResp struct {
	Title         string `json:"title" desc:"报告标题"`
	Content       string `json:"content" desc:"报告内容"`
	Abstract      string `json:"abstract" desc:"报告摘要"`
	Conclusion    string `json:"conclusion" desc:"结论"`
	NextSteps     string `json:"next_steps" desc:"下一步建议"`
	AchievementId int64  `json:"achievement_id" desc:"成果ID"`
	ShareUrl      string `json:"share_url" desc:"分享URL"`
}

type GenerateVideoReq struct {
	ProjectId int64    `json:"project_id" desc:"项目ID"`
	UserId    int64    `json:"user_id" desc:"用户ID"`
	Script    string   `json:"script" desc:"视频脚本"`
	Style     string   `json:"style,optional,default=educational" desc:"风格：educational,story,animation"`
	Duration  float64  `json:"duration,optional,default=60" desc:"期望时长(秒)"`
	Scenes    []string `json:"scenes,optional" desc:"场景描述"`
	Voice     string   `json:"voice,optional,default=female" desc:"语音类型"`
	Language  string   `json:"language,optional,default=zh-CN" desc:"语言"`
}

type GenerateVideoResp struct {
	VideoData     string        `json:"video_data" desc:"base64编码的视频数据"`
	Format        string        `json:"format" desc:"视频格式"`
	Duration      float64       `json:"duration" desc:"实际时长"`
	Metadata      VideoMetadata `json:"metadata" desc:"视频元数据"`
	AchievementId int64         `json:"achievement_id" desc:"成果ID"`
}

type GetProjectDetailReq struct {
	ProjectId int64 `json:"project_id" desc:"项目ID"`
	UserId    int64 `json:"user_id" desc:"用户ID"`
}

type GetProjectDetailResp struct {
	Project      ProjectDetail        `json:"project" desc:"项目详情"`
	Activities   []ProjectActivity    `json:"activities" desc:"项目活动记录"`
	Achievements []ProjectAchievement `json:"achievements" desc:"项目成果"`
}

type GetProjectListReq struct {
	UserId   int64  `json:"user_id" desc:"用户ID"`
	Category string `json:"category,optional" desc:"项目类别筛选"`
	Status   string `json:"status,optional" desc:"状态筛选：active,completed,paused"`
	PageSize int64  `json:"page_size,optional,default=10" desc:"每页条数"`
	Page     int64  `json:"page,optional,default=1" desc:"页码"`
}

type GetProjectListResp struct {
	List     []ProjectInfo `json:"list" desc:"项目列表"`
	Total    int64         `json:"total" desc:"总数"`
	PageSize int64         `json:"page_size" desc:"每页条数"`
	Page     int64         `json:"page" desc:"页码"`
}

type ObjectDetection struct {
	Timestamp  float64     `json:"timestamp" desc:"时间戳(秒)"`
	ObjectName string      `json:"object_name" desc:"物体名称"`
	Confidence float64     `json:"confidence" desc:"置信度"`
	Bbox       BoundingBox `json:"bbox" desc:"边界框"`
}

type ObservationInfo struct {
	ObservationId int64  `json:"observation_id" desc:"观察ID"`
	ImageUrl      string `json:"image_url" desc:"图片URL"`
	Recognition   string `json:"recognition" desc:"识别结果"`
	CreateTime    string `json:"create_time" desc:"创建时间"`
}

type PolishNoteReq struct {
	ProjectId   int64                 `json:"project_id" desc:"项目ID"`
	UserId      int64                 `json:"user_id" desc:"用户ID"`
	QuestionId  int64                 `json:"question_id" desc:"相关问题ID"`
	RawContent  string                `json:"raw_content" desc:"原始内容"`
	ContentType string                `json:"content_type" desc:"内容类型：speech,text"`
	ContextInfo map[string]interface{} `json:"context_info,optional" desc:"上下文信息对象"`
	Category    string                `json:"category" desc:"项目类别"`
	UserAge     int32                 `json:"user_age" desc:"用户年龄"`
}

type PolishNoteResp struct {
	Title            string   `json:"title" desc:"笔记标题"`
	Summary          string   `json:"summary" desc:"内容总结"`
	KeyPoints        []string `json:"key_points" desc:"关键要点"`
	FormattedText    string   `json:"formatted_text" desc:"格式化文本"`
	OriginalContent  string   `json:"original_content" desc:"原始内容"`
	PolishedNote     PolishedNote `json:"polished_note" desc:"润色后的笔记"`
	ExpressionId     int64    `json:"expression_id" desc:"表达记录ID"`
	Suggestions      []string `json:"suggestions" desc:"改进建议"`
	KeyLearnings     []string `json:"key_learnings" desc:"关键学习点"`
}

type PolishedNote struct {
	Title              string          `json:"title" desc:"笔记标题"`
	Summary            string          `json:"summary" desc:"内容总结"`
	KeyPoints          []string        `json:"key_points" desc:"关键要点"`
	ScientificConcepts []string        `json:"scientific_concepts" desc:"科学概念"`
	Questions          []string        `json:"questions" desc:"引发的疑问"`
	Connections        []string        `json:"connections" desc:"关联知识"`
	VisualElements     []VisualElement `json:"visual_elements" desc:"视觉元素"`
	FormattedText      string          `json:"formatted_text" desc:"格式化文本"`
}

type PosterDesign struct {
	Title          string          `json:"title" desc:"海报标题"`
	Style          string          `json:"style" desc:"设计风格"`
	Layout         string          `json:"layout" desc:"布局"`
	Sections       []PosterSection `json:"sections" desc:"海报区域"`
	ColorScheme    ColorScheme     `json:"color_scheme" desc:"配色方案"`
	Typography     Typography      `json:"typography" desc:"字体设计"`
	VisualElements []VisualElement `json:"visual_elements" desc:"视觉元素"`
}

type PosterSection struct {
	Type    string  `json:"type" desc:"区域类型：title,abstract,findings,visual,conclusion"`
	X       float64 `json:"x" desc:"X坐标(0-1)"`
	Y       float64 `json:"y" desc:"Y坐标(0-1)"`
	Width   float64 `json:"width" desc:"宽度(0-1)"`
	Height  float64 `json:"height" desc:"高度(0-1)"`
	Content string  `json:"content" desc:"区域内容"`
	Style   string  `json:"style" desc:"样式"`
}

type ProjectAchievement struct {
	AchievementId int64  `json:"achievement_id" desc:"成果ID"`
	Type          string `json:"type" desc:"成果类型：report,documentary,poster"`
	Title         string `json:"title" desc:"成果标题"`
	Content       string `json:"content" desc:"成果内容"`
	Url           string `json:"url,optional" desc:"成果URL"`
	CreateTime    string `json:"create_time" desc:"创建时间"`
}

type ProjectActivity struct {
	ActivityId  int64  `json:"activity_id" desc:"活动ID"`
	Type        string `json:"type" desc:"活动类型"`
	Description string `json:"description" desc:"活动描述"`
	CreateTime  string `json:"create_time" desc:"创建时间"`
}

type ProjectDetail struct {
	ProjectId    int64             `json:"project_id" desc:"项目ID"`
	ProjectCode  string            `json:"project_code" desc:"项目编码"`
	Title        string            `json:"title" desc:"项目标题"`
	Description  string            `json:"description" desc:"项目描述"`
	Category     string            `json:"category" desc:"项目类别"`
	Status       string            `json:"status" desc:"项目状态"`
	Progress     int32             `json:"progress" desc:"进度百分比"`
	CreateTime   string            `json:"create_time" desc:"创建时间"`
	UpdateTime   string            `json:"update_time" desc:"更新时间"`
	LastActivity string            `json:"last_activity" desc:"最后活动时间"`
	Tags         []string          `json:"tags" desc:"标签"`
	Observations []ObservationInfo `json:"observations" desc:"观察记录"`
	Questions    []QuestionInfo    `json:"questions" desc:"提问记录"`
	Expressions  []ExpressionInfo  `json:"expressions" desc:"表达记录"`
}

type ProjectInfo struct {
	ProjectId    int64    `json:"project_id" desc:"项目ID"`
	ProjectCode  string   `json:"project_code" desc:"项目编码"`
	Title        string   `json:"title" desc:"项目标题"`
	Description  string   `json:"description" desc:"项目描述"`
	Category     string   `json:"category" desc:"项目类别"`
	Status       string   `json:"status" desc:"项目状态"`
	Progress     int32    `json:"progress" desc:"进度百分比"`
	CreateTime   string   `json:"create_time" desc:"创建时间"`
	UpdateTime   string   `json:"update_time" desc:"更新时间"`
	LastActivity string   `json:"last_activity" desc:"最后活动时间"`
	Tags         []string `json:"tags" desc:"标签"`
}

type Question struct {
	QuestionId       int64    `json:"question_id" desc:"问题ID"`
	Content          string   `json:"content" desc:"问题内容"`
	Type             string   `json:"type" desc:"问题类型：observation,reasoning,experiment,comparison"`
	Difficulty       string   `json:"difficulty" desc:"难度级别：basic,intermediate,advanced"`
	Purpose          string   `json:"purpose" desc:"问题目的"`
	Hints            []string `json:"hints,optional" desc:"提示"`
	ExpectedThinking string   `json:"expected_thinking,optional" desc:"期望的思考方向"`
}

type QuestionInfo struct {
	QuestionId   int64  `json:"question_id" desc:"问题ID"`
	Question     string `json:"question" desc:"问题内容"`
	Answer       string `json:"answer" desc:"AI回答"`
	UserResponse string `json:"user_response,optional" desc:"用户回答"`
	CreateTime   string `json:"create_time" desc:"创建时间"`
}

type RecognitionResult struct {
	ObjectName     string         `json:"object_name" desc:"识别对象名称"`
	Category       string         `json:"category" desc:"类别"`
	Confidence     float64        `json:"confidence" desc:"置信度"`
	Description    string         `json:"description" desc:"描述"`
	KeyFeatures    []string       `json:"key_features" desc:"关键特征"`
	ScientificName string         `json:"scientific_name,optional" desc:"学名"`
	ARInfo         ARInformation  `json:"ar_info,optional" desc:"AR增强信息"`
	RelatedImages  []RelatedImage `json:"related_images,optional" desc:"相关图片"`
}

type RecognizeImageReq struct {
	ObservationId int64  `json:"observation_id,optional" desc:"观察记录ID（可选，不提供时自动创建）"`
	ProjectId     int64  `json:"project_id" desc:"项目ID"`
	UserId        int64  `json:"user_id" desc:"用户ID"`
	ImageUrl      string `json:"image_url" desc:"图片URL"`
	Prompt        string `json:"prompt,optional" desc:"分析提示"`
	Category      string `json:"category" desc:"项目类别"`
}

type RecognizeImageResp struct {
	ObjectName       string   `json:"object_name" desc:"识别出的物体名称"`
	Category         string   `json:"category" desc:"物体类别"`
	Confidence       float64  `json:"confidence" desc:"识别置信度"`
	Description      string   `json:"description" desc:"物体描述"`
	KeyFeatures      []string `json:"key_features" desc:"关键特征"`
	ScientificName   string   `json:"scientific_name,optional" desc:"科学名称"`
	ObservationId    int64    `json:"observation_id" desc:"观察记录ID"`
	Recognition      RecognitionResult `json:"recognition" desc:"识别结果"`
	Suggestions      []string `json:"suggestions" desc:"AI建议的观察要点"`
	NextActions      []string `json:"next_actions" desc:"建议的下一步行动"`
	InterestingFacts []string `json:"interesting_facts" desc:"有趣的事实"`
}

type Reference struct {
	Title  string `json:"title" desc:"资料标题"`
	Type   string `json:"type" desc:"资料类型：book,article,video,website"`
	Url    string `json:"url,optional" desc:"资料URL"`
	Credit string `json:"credit" desc:"资料来源"`
}

type RelatedImage struct {
	Url         string `json:"url" desc:"图片URL"`
	Title       string `json:"title" desc:"图片标题"`
	Description string `json:"description" desc:"图片描述"`
	Credit      string `json:"credit" desc:"图片来源"`
}

type ReportVisual struct {
	Type        string `json:"type" desc:"视觉类型：chart,diagram,timeline,map"`
	Title       string `json:"title" desc:"视觉标题"`
	Description string `json:"description" desc:"视觉描述"`
	Data        string `json:"data" desc:"视觉数据(JSON格式)"`
}

type ResearchReport struct {
	Title         string         `json:"title" desc:"报告标题"`
	Abstract      string         `json:"abstract" desc:"摘要"`
	Introduction  string         `json:"introduction" desc:"引言"`
	Methodology   string         `json:"methodology" desc:"研究方法"`
	Findings      []Finding      `json:"findings" desc:"发现与结果"`
	Discussion    string         `json:"discussion" desc:"讨论"`
	Conclusion    string         `json:"conclusion" desc:"结论"`
	References    []Reference    `json:"references" desc:"参考资料"`
	Visuals       []ReportVisual `json:"visuals" desc:"视觉元素"`
	ChildInsights string         `json:"child_insights" desc:"孩子的独特见解"`
	NextSteps     []string       `json:"next_steps" desc:"下一步探索建议"`
}

type Scene struct {
	SceneNumber int32    `json:"scene_number" desc:"场景编号"`
	Duration    int32    `json:"duration" desc:"场景时长(秒)"`
	Description string   `json:"description" desc:"场景描述"`
	Visuals     []string `json:"visuals" desc:"视觉元素"`
	Narration   string   `json:"narration" desc:"场景旁白"`
	Transitions string   `json:"transitions,optional" desc:"转场效果"`
}

type SceneAnalysis struct {
	Timestamp   float64 `json:"timestamp" desc:"时间戳(秒)"`
	SceneType   string  `json:"scene_type" desc:"场景类型"`
	Confidence  float64 `json:"confidence" desc:"置信度"`
	Description string  `json:"description" desc:"场景描述"`
}

type SelectQuestionReq struct {
	ProjectId  int64 `json:"project_id" desc:"项目ID"`
	UserId     int64 `json:"user_id" desc:"用户ID"`
	QuestionId int64 `json:"question_id" desc:"选择的问题ID"`
}

type SelectQuestionResp struct {
	QuestionId        int64      `json:"question_id" desc:"问题ID"`
	Question          string     `json:"question" desc:"问题内容"`
	AIResponse        AIResponse `json:"ai_response" desc:"AI回答"`
	FollowUpQuestions []string   `json:"follow_up_questions" desc:"后续问题建议"`
	ThinkingPrompts   []string   `json:"thinking_prompts" desc:"思考提示"`
	Activities        []Activity `json:"activities" desc:"建议活动"`
}

type SpeechToTextReq struct {
	ProjectId   int64  `json:"project_id" desc:"项目ID"`
	UserId      int64  `json:"user_id" desc:"用户ID"`
	AudioData   string `json:"audio_data" desc:"base64编码的音频数据"`
	AudioFormat string `json:"audio_format" desc:"音频格式：wav,mp3,m4a"`
	Language    string `json:"language,optional,default=zh-CN" desc:"语言代码"`
}

type SpeechToTextResp struct {
	Text         string  `json:"text" desc:"转换后的文字"`
	Confidence   float64 `json:"confidence" desc:"识别置信度"`
	Duration     float64 `json:"duration" desc:"音频时长(秒)"`
	Language     string  `json:"language" desc:"检测到的语言"`
	ExpressionId int64   `json:"expression_id" desc:"表达记录ID"`
}

type TextRecognition struct {
	Timestamp  float64     `json:"timestamp" desc:"时间戳(秒)"`
	Text       string      `json:"text" desc:"识别出的文字"`
	Language   string      `json:"language" desc:"语言"`
	Confidence float64     `json:"confidence" desc:"置信度"`
	Bbox       BoundingBox `json:"bbox" desc:"文字位置"`
}

type TextToSpeechReq struct {
	ProjectId int64   `json:"project_id" desc:"项目ID"`
	UserId    int64   `json:"user_id" desc:"用户ID"`
	Text      string  `json:"text" desc:"要转换的文字"`
	Voice     string  `json:"voice,optional,default=female" desc:"语音类型：female,male"`
	Language  string  `json:"language,optional,default=zh-CN" desc:"语言代码"`
	Speed     float64 `json:"speed,optional,default=1.0" desc:"语速，1.0为正常语速"`
}

type TextToSpeechResp struct {
	AudioData    string  `json:"audio_data" desc:"base64编码的音频数据"`
	Format       string  `json:"format" desc:"音频格式：wav,mp3"`
	Duration     float64 `json:"duration" desc:"音频时长(秒)"`
	ExpressionId int64   `json:"expression_id" desc:"表达记录ID"`
}

type Typography struct {
	TitleFont   string `json:"title_font" desc:"标题字体"`
	BodyFont    string `json:"body_font" desc:"正文字体"`
	HeadingFont string `json:"heading_font" desc:"标题字体"`
	TitleSize   int32  `json:"title_size" desc:"标题字号"`
	BodySize    int32  `json:"body_size" desc:"正文字号"`
	HeadingSize int32  `json:"heading_size" desc:"标题字号"`
}

type UpdateProjectStatusReq struct {
	ProjectId int64  `json:"project_id" desc:"项目ID"`
	UserId    int64  `json:"user_id" desc:"用户ID"`
	Status    string `json:"status" desc:"新状态：active,completed,paused"`
}

type UploadObservationImageReq struct {
	ProjectId int64  `json:"project_id" desc:"项目ID"`
	UserId    int64  `json:"user_id" desc:"用户ID"`
	ImageData string `json:"image_data" desc:"base64编码的图片数据"`
	ImageName string `json:"image_name" desc:"图片名称"`
	ImageType string `json:"image_type" desc:"图片类型：jpeg,png,jpg"`
}

type UploadObservationImageResp struct {
	ObservationId int64  `json:"observation_id" desc:"观察记录ID"`
	ImageUrl      string `json:"image_url" desc:"图片访问URL"`
	Status        string `json:"status" desc:"上传状态"`
}

type VideoAnalysisResult struct {
	Scenes   []SceneAnalysis   `json:"scenes" desc:"场景分析结果"`
	Objects  []ObjectDetection `json:"objects" desc:"物体检测结果"`
	Emotions []EmotionAnalysis `json:"emotions" desc:"情感分析结果"`
	Texts    []TextRecognition `json:"texts" desc:"文字识别结果"`
	Audio    []AudioAnalysis   `json:"audio" desc:"音频分析结果"`
	Summary  VideoSummary      `json:"summary" desc:"视频总结"`
}

type VideoMetadata struct {
	Title         string   `json:"title" desc:"视频标题"`
	Description   string   `json:"description" desc:"视频描述"`
	Scenes        []string `json:"scenes" desc:"生成场景列表"`
	AudioLanguage string   `json:"audio_language" desc:"音频语言"`
	Resolution    string   `json:"resolution" desc:"分辨率"`
}

type VideoSummary struct {
	Title       string   `json:"title" desc:"视频标题"`
	Description string   `json:"description" desc:"视频描述"`
	Keywords    []string `json:"keywords" desc:"关键词"`
	Category    string   `json:"category" desc:"视频类别"`
	Duration    float64  `json:"duration" desc:"视频总时长"`
}

type VisualElement struct {
	Type        string `json:"type" desc:"元素类型：diagram,illustration,chart,mindmap"`
	Title       string `json:"title" desc:"元素标题"`
	Description string `json:"description" desc:"元素描述"`
	Data        string `json:"data" desc:"元素数据(JSON格式)"`
	Position    string `json:"position" desc:"位置建议"`
}
