// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7

package handler

import (
	"net/http"

	achievement "explorapal/app/api/internal/handler/achievement"
	audio "explorapal/app/api/internal/handler/audio"
	common "explorapal/app/api/internal/handler/common"
	expression "explorapal/app/api/internal/handler/expression"
	observation "explorapal/app/api/internal/handler/observation"
	project "explorapal/app/api/internal/handler/project"
	questioning "explorapal/app/api/internal/handler/questioning"
	"explorapal/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					// 生成纪录片脚本
					Method:  http.MethodPost,
					Path:    "/documentary/generate",
					Handler: achievement.GenerateDocumentaryHandler(serverCtx),
				},
				{
					// 生成学术海报
					Method:  http.MethodPost,
					Path:    "/poster/generate",
					Handler: achievement.GeneratePosterHandler(serverCtx),
				},
				{
					// 生成研究简报
					Method:  http.MethodPost,
					Path:    "/report/generate",
					Handler: achievement.GenerateReportHandler(serverCtx),
				},
				{
					// 分析视频内容
					Method:  http.MethodPost,
					Path:    "/video/analyze",
					Handler: achievement.AnalyzeVideoHandler(serverCtx),
				},
				{
					// 生成AI视频
					Method:  http.MethodPost,
					Path:    "/video/generate",
					Handler: achievement.GenerateVideoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/achievement"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					// 文字转语音
					Method:  http.MethodPost,
					Path:    "/text-to-speech",
					Handler: audio.TextToSpeechHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/audio"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 健康检查
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: common.PingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/common"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					// AI润色生成笔记
					Method:  http.MethodPost,
					Path:    "/note/polish",
					Handler: expression.PolishNoteHandler(serverCtx),
				},
				{
					// 语音转文字
					Method:  http.MethodPost,
					Path:    "/speech/text",
					Handler: expression.SpeechToTextHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/expression"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					// 识别图片内容
					Method:  http.MethodPost,
					Path:    "/image/recognize",
					Handler: observation.RecognizeImageHandler(serverCtx),
				},
				{
					// 上传观察图片
					Method:  http.MethodPost,
					Path:    "/image/upload",
					Handler: observation.UploadObservationImageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/observation"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					// 创建探索项目
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: project.CreateProjectHandler(serverCtx),
				},
				{
					// 获取项目详情
					Method:  http.MethodPost,
					Path:    "/detail",
					Handler: project.GetProjectDetailHandler(serverCtx),
				},
				{
					// 获取项目列表
					Method:  http.MethodPost,
					Path:    "/list",
					Handler: project.GetProjectListHandler(serverCtx),
				},
				{
					// 更新项目状态
					Method:  http.MethodPost,
					Path:    "/status/update",
					Handler: project.UpdateProjectStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/project"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					// 选择问题并获取AI回答
					Method:  http.MethodPost,
					Path:    "/question/select",
					Handler: questioning.SelectQuestionHandler(serverCtx),
				},
				{
					// 生成引导问题
					Method:  http.MethodPost,
					Path:    "/questions/generate",
					Handler: questioning.GenerateQuestionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/questioning"),
	)
}
