// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: app/project-management/rpc/project-management.proto

package projectmanagement

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ProjectManagementService_CreateProject_FullMethodName       = "/projectmanagement.ProjectManagementService/CreateProject"
	ProjectManagementService_GetProjectList_FullMethodName      = "/projectmanagement.ProjectManagementService/GetProjectList"
	ProjectManagementService_GetProjectDetail_FullMethodName    = "/projectmanagement.ProjectManagementService/GetProjectDetail"
	ProjectManagementService_UpdateProjectStatus_FullMethodName = "/projectmanagement.ProjectManagementService/UpdateProjectStatus"
)

// ProjectManagementServiceClient is the client API for ProjectManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectManagementServiceClient interface {
	CreateProject(ctx context.Context, in *CreateProjectReq, opts ...grpc.CallOption) (*CreateProjectResp, error)
	GetProjectList(ctx context.Context, in *GetProjectListReq, opts ...grpc.CallOption) (*GetProjectListResp, error)
	GetProjectDetail(ctx context.Context, in *GetProjectDetailReq, opts ...grpc.CallOption) (*GetProjectDetailResp, error)
	UpdateProjectStatus(ctx context.Context, in *UpdateProjectStatusReq, opts ...grpc.CallOption) (*UpdateProjectStatusResp, error)
}

type projectManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectManagementServiceClient(cc grpc.ClientConnInterface) ProjectManagementServiceClient {
	return &projectManagementServiceClient{cc}
}

func (c *projectManagementServiceClient) CreateProject(ctx context.Context, in *CreateProjectReq, opts ...grpc.CallOption) (*CreateProjectResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProjectResp)
	err := c.cc.Invoke(ctx, ProjectManagementService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementServiceClient) GetProjectList(ctx context.Context, in *GetProjectListReq, opts ...grpc.CallOption) (*GetProjectListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectListResp)
	err := c.cc.Invoke(ctx, ProjectManagementService_GetProjectList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementServiceClient) GetProjectDetail(ctx context.Context, in *GetProjectDetailReq, opts ...grpc.CallOption) (*GetProjectDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectDetailResp)
	err := c.cc.Invoke(ctx, ProjectManagementService_GetProjectDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementServiceClient) UpdateProjectStatus(ctx context.Context, in *UpdateProjectStatusReq, opts ...grpc.CallOption) (*UpdateProjectStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProjectStatusResp)
	err := c.cc.Invoke(ctx, ProjectManagementService_UpdateProjectStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectManagementServiceServer is the server API for ProjectManagementService service.
// All implementations must embed UnimplementedProjectManagementServiceServer
// for forward compatibility.
type ProjectManagementServiceServer interface {
	CreateProject(context.Context, *CreateProjectReq) (*CreateProjectResp, error)
	GetProjectList(context.Context, *GetProjectListReq) (*GetProjectListResp, error)
	GetProjectDetail(context.Context, *GetProjectDetailReq) (*GetProjectDetailResp, error)
	UpdateProjectStatus(context.Context, *UpdateProjectStatusReq) (*UpdateProjectStatusResp, error)
	mustEmbedUnimplementedProjectManagementServiceServer()
}

// UnimplementedProjectManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectManagementServiceServer struct{}

func (UnimplementedProjectManagementServiceServer) CreateProject(context.Context, *CreateProjectReq) (*CreateProjectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedProjectManagementServiceServer) GetProjectList(context.Context, *GetProjectListReq) (*GetProjectListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectList not implemented")
}
func (UnimplementedProjectManagementServiceServer) GetProjectDetail(context.Context, *GetProjectDetailReq) (*GetProjectDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectDetail not implemented")
}
func (UnimplementedProjectManagementServiceServer) UpdateProjectStatus(context.Context, *UpdateProjectStatusReq) (*UpdateProjectStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectStatus not implemented")
}
func (UnimplementedProjectManagementServiceServer) mustEmbedUnimplementedProjectManagementServiceServer() {
}
func (UnimplementedProjectManagementServiceServer) testEmbeddedByValue() {}

// UnsafeProjectManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectManagementServiceServer will
// result in compilation errors.
type UnsafeProjectManagementServiceServer interface {
	mustEmbedUnimplementedProjectManagementServiceServer()
}

func RegisterProjectManagementServiceServer(s grpc.ServiceRegistrar, srv ProjectManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedProjectManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectManagementService_ServiceDesc, srv)
}

func _ProjectManagementService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectManagementService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementServiceServer).CreateProject(ctx, req.(*CreateProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementService_GetProjectList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementServiceServer).GetProjectList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectManagementService_GetProjectList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementServiceServer).GetProjectList(ctx, req.(*GetProjectListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementService_GetProjectDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementServiceServer).GetProjectDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectManagementService_GetProjectDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementServiceServer).GetProjectDetail(ctx, req.(*GetProjectDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementService_UpdateProjectStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementServiceServer).UpdateProjectStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectManagementService_UpdateProjectStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementServiceServer).UpdateProjectStatus(ctx, req.(*UpdateProjectStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectManagementService_ServiceDesc is the grpc.ServiceDesc for ProjectManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "projectmanagement.ProjectManagementService",
	HandlerType: (*ProjectManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _ProjectManagementService_CreateProject_Handler,
		},
		{
			MethodName: "GetProjectList",
			Handler:    _ProjectManagementService_GetProjectList_Handler,
		},
		{
			MethodName: "GetProjectDetail",
			Handler:    _ProjectManagementService_GetProjectDetail_Handler,
		},
		{
			MethodName: "UpdateProjectStatus",
			Handler:    _ProjectManagementService_UpdateProjectStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/project-management/rpc/project-management.proto",
}
