// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.7

package hps

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	achievementsFieldNames          = builder.RawFieldNames(&Achievements{})
	achievementsRows                = strings.Join(achievementsFieldNames, ",")
	achievementsRowsExpectAutoSet   = strings.Join(stringx.Remove(achievementsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	achievementsRowsWithPlaceHolder = strings.Join(stringx.Remove(achievementsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAchievementsIdPrefix            = "cache:achievements:id:"
	cacheAchievementsAchievementIdPrefix = "cache:achievements:achievementId:"
)

type (
	achievementsModel interface {
		Insert(ctx context.Context, data *Achievements) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Achievements, error)
		FindOneByAchievementId(ctx context.Context, achievementId int64) (*Achievements, error)
		Update(ctx context.Context, data *Achievements) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAchievementsModel struct {
		sqlc.CachedConn
		table string
	}

	Achievements struct {
		Id            uint64         `db:"id"`             // 主键ID
		CreateTime    time.Time      `db:"create_time"`    // 创建时间
		UpdateTime    time.Time      `db:"update_time"`    // 更新时间
		DeleteTime    sql.NullTime   `db:"delete_time"`    // 删除时间
		AchievementId int64          `db:"achievement_id"` // 成果ID
		ProjectId     int64          `db:"project_id"`     // 项目ID
		UserId        int64          `db:"user_id"`        // 用户ID
		Type          string         `db:"type"`           // 成果类型：report,documentary,poster
		Title         string         `db:"title"`          // 成果标题
		Description   sql.NullString `db:"description"`    // 成果描述
		Content       string         `db:"content"`        // 成果内容JSON
		Url           sql.NullString `db:"url"`            // 成果URL
		FileSize      sql.NullInt64  `db:"file_size"`      // 文件大小(字节)
		Style         sql.NullString `db:"style"`          // 风格参数
		Layout        sql.NullString `db:"layout"`         // 布局参数
		Length        sql.NullString `db:"length"`         // 时长参数
		Status        string         `db:"status"`         // 状态：generating,completed,failed
		ErrorMsg      sql.NullString `db:"error_msg"`      // 错误信息
		ViewCount     int64          `db:"view_count"`     // 查看次数
		LikeCount     int64          `db:"like_count"`     // 点赞次数
		ShareCount    int64          `db:"share_count"`    // 分享次数
	}
)

func newAchievementsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAchievementsModel {
	return &defaultAchievementsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`achievements`",
	}
}

func (m *defaultAchievementsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	achievementsAchievementIdKey := fmt.Sprintf("%s%v", cacheAchievementsAchievementIdPrefix, data.AchievementId)
	achievementsIdKey := fmt.Sprintf("%s%v", cacheAchievementsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, achievementsAchievementIdKey, achievementsIdKey)
	return err
}

func (m *defaultAchievementsModel) FindOne(ctx context.Context, id uint64) (*Achievements, error) {
	achievementsIdKey := fmt.Sprintf("%s%v", cacheAchievementsIdPrefix, id)
	var resp Achievements
	err := m.QueryRowCtx(ctx, &resp, achievementsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", achievementsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAchievementsModel) FindOneByAchievementId(ctx context.Context, achievementId int64) (*Achievements, error) {
	achievementsAchievementIdKey := fmt.Sprintf("%s%v", cacheAchievementsAchievementIdPrefix, achievementId)
	var resp Achievements
	err := m.QueryRowIndexCtx(ctx, &resp, achievementsAchievementIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `achievement_id` = ? limit 1", achievementsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, achievementId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAchievementsModel) Insert(ctx context.Context, data *Achievements) (sql.Result, error) {
	achievementsAchievementIdKey := fmt.Sprintf("%s%v", cacheAchievementsAchievementIdPrefix, data.AchievementId)
	achievementsIdKey := fmt.Sprintf("%s%v", cacheAchievementsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, achievementsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.AchievementId, data.ProjectId, data.UserId, data.Type, data.Title, data.Description, data.Content, data.Url, data.FileSize, data.Style, data.Layout, data.Length, data.Status, data.ErrorMsg, data.ViewCount, data.LikeCount, data.ShareCount)
	}, achievementsAchievementIdKey, achievementsIdKey)
	return ret, err
}

func (m *defaultAchievementsModel) Update(ctx context.Context, newData *Achievements) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	achievementsAchievementIdKey := fmt.Sprintf("%s%v", cacheAchievementsAchievementIdPrefix, data.AchievementId)
	achievementsIdKey := fmt.Sprintf("%s%v", cacheAchievementsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, achievementsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeleteTime, newData.AchievementId, newData.ProjectId, newData.UserId, newData.Type, newData.Title, newData.Description, newData.Content, newData.Url, newData.FileSize, newData.Style, newData.Layout, newData.Length, newData.Status, newData.ErrorMsg, newData.ViewCount, newData.LikeCount, newData.ShareCount, newData.Id)
	}, achievementsAchievementIdKey, achievementsIdKey)
	return err
}

func (m *defaultAchievementsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAchievementsIdPrefix, primary)
}

func (m *defaultAchievementsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", achievementsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAchievementsModel) tableName() string {
	return m.table
}
