// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.7

package hps

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	expressionsFieldNames          = builder.RawFieldNames(&Expressions{})
	expressionsRows                = strings.Join(expressionsFieldNames, ",")
	expressionsRowsExpectAutoSet   = strings.Join(stringx.Remove(expressionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	expressionsRowsWithPlaceHolder = strings.Join(stringx.Remove(expressionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheExpressionsIdPrefix           = "cache:expressions:id:"
	cacheExpressionsExpressionIdPrefix = "cache:expressions:expressionId:"
)

type (
	expressionsModel interface {
		Insert(ctx context.Context, data *Expressions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Expressions, error)
		FindOneByExpressionId(ctx context.Context, expressionId int64) (*Expressions, error)
		Update(ctx context.Context, data *Expressions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultExpressionsModel struct {
		sqlc.CachedConn
		table string
	}

	Expressions struct {
		Id                  uint64          `db:"id"`                   // 主键ID
		CreateTime          time.Time       `db:"create_time"`          // 创建时间
		UpdateTime          time.Time       `db:"update_time"`          // 更新时间
		DeleteTime          sql.NullTime    `db:"delete_time"`          // 删除时间
		ExpressionId        int64           `db:"expression_id"`        // 表达记录ID
		ProjectId           int64           `db:"project_id"`           // 项目ID
		UserId              int64           `db:"user_id"`              // 用户ID
		QuestionId          sql.NullInt64   `db:"question_id"`          // 关联的问题ID
		Type                string          `db:"type"`                 // 类型：speech,text,note
		RawContent          string          `db:"raw_content"`          // 原始内容
		Language            string          `db:"language"`             // 语言代码
		AudioUrl            sql.NullString  `db:"audio_url"`            // 音频URL
		AudioFormat         sql.NullString  `db:"audio_format"`         // 音频格式：wav,mp3,m4a
		AudioSize           sql.NullInt64   `db:"audio_size"`           // 音频大小(字节)
		Duration            sql.NullFloat64 `db:"duration"`             // 音频时长(秒)
		Confidence          sql.NullFloat64 `db:"confidence"`           // 识别置信度
		PolishedTitle       sql.NullString  `db:"polished_title"`       // 润色后的标题
		PolishedSummary     sql.NullString  `db:"polished_summary"`     // 内容总结
		PolishedKeyPoints   sql.NullString  `db:"polished_key_points"`  // 关键要点JSON数组
		PolishedConcepts    sql.NullString  `db:"polished_concepts"`    // 科学概念JSON数组
		PolishedQuestions   sql.NullString  `db:"polished_questions"`   // 引发的疑问JSON数组
		PolishedConnections sql.NullString  `db:"polished_connections"` // 关联知识JSON数组
		PolishedVisuals     sql.NullString  `db:"polished_visuals"`     // 视觉元素JSON数组
		PolishedFormatted   sql.NullString  `db:"polished_formatted"`   // 格式化文本
		Suggestions         sql.NullString  `db:"suggestions"`          // 改进建议JSON数组
		KeyLearnings        sql.NullString  `db:"key_learnings"`        // 关键学习点JSON数组
	}
)

func newExpressionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultExpressionsModel {
	return &defaultExpressionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`expressions`",
	}
}

func (m *defaultExpressionsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	expressionsExpressionIdKey := fmt.Sprintf("%s%v", cacheExpressionsExpressionIdPrefix, data.ExpressionId)
	expressionsIdKey := fmt.Sprintf("%s%v", cacheExpressionsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, expressionsExpressionIdKey, expressionsIdKey)
	return err
}

func (m *defaultExpressionsModel) FindOne(ctx context.Context, id uint64) (*Expressions, error) {
	expressionsIdKey := fmt.Sprintf("%s%v", cacheExpressionsIdPrefix, id)
	var resp Expressions
	err := m.QueryRowCtx(ctx, &resp, expressionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", expressionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultExpressionsModel) FindOneByExpressionId(ctx context.Context, expressionId int64) (*Expressions, error) {
	expressionsExpressionIdKey := fmt.Sprintf("%s%v", cacheExpressionsExpressionIdPrefix, expressionId)
	var resp Expressions
	err := m.QueryRowIndexCtx(ctx, &resp, expressionsExpressionIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `expression_id` = ? limit 1", expressionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, expressionId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultExpressionsModel) Insert(ctx context.Context, data *Expressions) (sql.Result, error) {
	expressionsExpressionIdKey := fmt.Sprintf("%s%v", cacheExpressionsExpressionIdPrefix, data.ExpressionId)
	expressionsIdKey := fmt.Sprintf("%s%v", cacheExpressionsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, expressionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.ExpressionId, data.ProjectId, data.UserId, data.QuestionId, data.Type, data.RawContent, data.Language, data.AudioUrl, data.AudioFormat, data.AudioSize, data.Duration, data.Confidence, data.PolishedTitle, data.PolishedSummary, data.PolishedKeyPoints, data.PolishedConcepts, data.PolishedQuestions, data.PolishedConnections, data.PolishedVisuals, data.PolishedFormatted, data.Suggestions, data.KeyLearnings)
	}, expressionsExpressionIdKey, expressionsIdKey)
	return ret, err
}

func (m *defaultExpressionsModel) Update(ctx context.Context, newData *Expressions) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	expressionsExpressionIdKey := fmt.Sprintf("%s%v", cacheExpressionsExpressionIdPrefix, data.ExpressionId)
	expressionsIdKey := fmt.Sprintf("%s%v", cacheExpressionsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, expressionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeleteTime, newData.ExpressionId, newData.ProjectId, newData.UserId, newData.QuestionId, newData.Type, newData.RawContent, newData.Language, newData.AudioUrl, newData.AudioFormat, newData.AudioSize, newData.Duration, newData.Confidence, newData.PolishedTitle, newData.PolishedSummary, newData.PolishedKeyPoints, newData.PolishedConcepts, newData.PolishedQuestions, newData.PolishedConnections, newData.PolishedVisuals, newData.PolishedFormatted, newData.Suggestions, newData.KeyLearnings, newData.Id)
	}, expressionsExpressionIdKey, expressionsIdKey)
	return err
}

func (m *defaultExpressionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheExpressionsIdPrefix, primary)
}

func (m *defaultExpressionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", expressionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultExpressionsModel) tableName() string {
	return m.table
}
