// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.7

package hps

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	observationsFieldNames          = builder.RawFieldNames(&Observations{})
	observationsRows                = strings.Join(observationsFieldNames, ",")
	observationsRowsExpectAutoSet   = strings.Join(stringx.Remove(observationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	observationsRowsWithPlaceHolder = strings.Join(stringx.Remove(observationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheObservationsIdPrefix            = "cache:observations:id:"
	cacheObservationsObservationIdPrefix = "cache:observations:observationId:"
)

type (
	observationsModel interface {
		Insert(ctx context.Context, data *Observations) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Observations, error)
		FindOneByObservationId(ctx context.Context, observationId int64) (*Observations, error)
		Update(ctx context.Context, data *Observations) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultObservationsModel struct {
		sqlc.CachedConn
		table string
	}

	Observations struct {
		Id               uint64          `db:"id"`                // 主键ID
		CreateTime       time.Time       `db:"create_time"`       // 创建时间
		UpdateTime       time.Time       `db:"update_time"`       // 更新时间
		DeleteTime       sql.NullTime    `db:"delete_time"`       // 删除时间
		ObservationId    int64           `db:"observation_id"`    // 观察记录ID
		ProjectId        int64           `db:"project_id"`        // 项目ID
		UserId           int64           `db:"user_id"`           // 用户ID
		ImageUrl         string          `db:"image_url"`         // 图片URL
		ImageName        sql.NullString  `db:"image_name"`        // 图片名称
		ImageType        sql.NullString  `db:"image_type"`        // 图片类型：jpeg,png,jpg
		ImageSize        sql.NullInt64   `db:"image_size"`        // 图片大小(字节)
		ObjectName       sql.NullString  `db:"object_name"`       // 识别对象名称
		Category         sql.NullString  `db:"category"`          // 类别
		Confidence       sql.NullFloat64 `db:"confidence"`        // 置信度
		Description      sql.NullString  `db:"description"`       // 描述
		KeyFeatures      sql.NullString  `db:"key_features"`      // 关键特征JSON数组
		ScientificName   sql.NullString  `db:"scientific_name"`   // 学名
		ArInfo           sql.NullString  `db:"ar_info"`           // AR信息JSON
		Suggestions      sql.NullString  `db:"suggestions"`       // AI建议JSON数组
		InterestingFacts sql.NullString  `db:"interesting_facts"` // 有趣事实JSON数组
	}
)

func newObservationsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultObservationsModel {
	return &defaultObservationsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`observations`",
	}
}

func (m *defaultObservationsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	observationsIdKey := fmt.Sprintf("%s%v", cacheObservationsIdPrefix, id)
	observationsObservationIdKey := fmt.Sprintf("%s%v", cacheObservationsObservationIdPrefix, data.ObservationId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, observationsIdKey, observationsObservationIdKey)
	return err
}

func (m *defaultObservationsModel) FindOne(ctx context.Context, id uint64) (*Observations, error) {
	observationsIdKey := fmt.Sprintf("%s%v", cacheObservationsIdPrefix, id)
	var resp Observations
	err := m.QueryRowCtx(ctx, &resp, observationsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", observationsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultObservationsModel) FindOneByObservationId(ctx context.Context, observationId int64) (*Observations, error) {
	observationsObservationIdKey := fmt.Sprintf("%s%v", cacheObservationsObservationIdPrefix, observationId)
	var resp Observations
	err := m.QueryRowIndexCtx(ctx, &resp, observationsObservationIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `observation_id` = ? limit 1", observationsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, observationId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultObservationsModel) Insert(ctx context.Context, data *Observations) (sql.Result, error) {
	observationsIdKey := fmt.Sprintf("%s%v", cacheObservationsIdPrefix, data.Id)
	observationsObservationIdKey := fmt.Sprintf("%s%v", cacheObservationsObservationIdPrefix, data.ObservationId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, observationsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.ObservationId, data.ProjectId, data.UserId, data.ImageUrl, data.ImageName, data.ImageType, data.ImageSize, data.ObjectName, data.Category, data.Confidence, data.Description, data.KeyFeatures, data.ScientificName, data.ArInfo, data.Suggestions, data.InterestingFacts)
	}, observationsIdKey, observationsObservationIdKey)
	return ret, err
}

func (m *defaultObservationsModel) Update(ctx context.Context, newData *Observations) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	observationsIdKey := fmt.Sprintf("%s%v", cacheObservationsIdPrefix, data.Id)
	observationsObservationIdKey := fmt.Sprintf("%s%v", cacheObservationsObservationIdPrefix, data.ObservationId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, observationsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeleteTime, newData.ObservationId, newData.ProjectId, newData.UserId, newData.ImageUrl, newData.ImageName, newData.ImageType, newData.ImageSize, newData.ObjectName, newData.Category, newData.Confidence, newData.Description, newData.KeyFeatures, newData.ScientificName, newData.ArInfo, newData.Suggestions, newData.InterestingFacts, newData.Id)
	}, observationsIdKey, observationsObservationIdKey)
	return err
}

func (m *defaultObservationsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheObservationsIdPrefix, primary)
}

func (m *defaultObservationsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", observationsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultObservationsModel) tableName() string {
	return m.table
}
