// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.7

package hps

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	projectsFieldNames          = builder.RawFieldNames(&Projects{})
	projectsRows                = strings.Join(projectsFieldNames, ",")
	projectsRowsExpectAutoSet   = strings.Join(stringx.Remove(projectsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	projectsRowsWithPlaceHolder = strings.Join(stringx.Remove(projectsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheProjectsIdPrefix          = "cache:projects:id:"
	cacheProjectsProjectCodePrefix = "cache:projects:projectCode:"
	cacheProjectsProjectIdPrefix   = "cache:projects:projectId:"
)

type (
	projectsModel interface {
		Insert(ctx context.Context, data *Projects) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Projects, error)
		FindOneByProjectCode(ctx context.Context, projectCode string) (*Projects, error)
		FindOneByProjectId(ctx context.Context, projectId int64) (*Projects, error)
		Update(ctx context.Context, data *Projects) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProjectsModel struct {
		sqlc.CachedConn
		table string
	}

	Projects struct {
		Id             uint64         `db:"id"`               // 主键ID
		CreateTime     time.Time      `db:"create_time"`      // 创建时间
		UpdateTime     time.Time      `db:"update_time"`      // 更新时间
		DeleteTime     sql.NullTime   `db:"delete_time"`      // 删除时间
		ProjectId      int64          `db:"project_id"`       // 项目ID
		ProjectCode    string         `db:"project_code"`     // 项目编码
		UserId         int64          `db:"user_id"`          // 用户ID
		Title          string         `db:"title"`            // 项目标题
		Description    sql.NullString `db:"description"`      // 项目描述
		Category       string         `db:"category"`         // 项目类别
		Status         string         `db:"status"`           // 状态：active,completed,paused
		Progress       int64          `db:"progress"`         // 进度百分比(0-100)
		Tags           sql.NullString `db:"tags"`             // 标签JSON数组
		LastActivityAt sql.NullTime   `db:"last_activity_at"` // 最后活动时间
	}
)

func newProjectsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProjectsModel {
	return &defaultProjectsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`projects`",
	}
}

func (m *defaultProjectsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	projectsIdKey := fmt.Sprintf("%s%v", cacheProjectsIdPrefix, id)
	projectsProjectCodeKey := fmt.Sprintf("%s%v", cacheProjectsProjectCodePrefix, data.ProjectCode)
	projectsProjectIdKey := fmt.Sprintf("%s%v", cacheProjectsProjectIdPrefix, data.ProjectId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, projectsIdKey, projectsProjectCodeKey, projectsProjectIdKey)
	return err
}

func (m *defaultProjectsModel) FindOne(ctx context.Context, id uint64) (*Projects, error) {
	projectsIdKey := fmt.Sprintf("%s%v", cacheProjectsIdPrefix, id)
	var resp Projects
	err := m.QueryRowCtx(ctx, &resp, projectsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", projectsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProjectsModel) FindOneByProjectCode(ctx context.Context, projectCode string) (*Projects, error) {
	projectsProjectCodeKey := fmt.Sprintf("%s%v", cacheProjectsProjectCodePrefix, projectCode)
	var resp Projects
	err := m.QueryRowIndexCtx(ctx, &resp, projectsProjectCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `project_code` = ? limit 1", projectsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, projectCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProjectsModel) FindOneByProjectId(ctx context.Context, projectId int64) (*Projects, error) {
	projectsProjectIdKey := fmt.Sprintf("%s%v", cacheProjectsProjectIdPrefix, projectId)
	var resp Projects
	err := m.QueryRowIndexCtx(ctx, &resp, projectsProjectIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `project_id` = ? limit 1", projectsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, projectId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProjectsModel) Insert(ctx context.Context, data *Projects) (sql.Result, error) {
	projectsIdKey := fmt.Sprintf("%s%v", cacheProjectsIdPrefix, data.Id)
	projectsProjectCodeKey := fmt.Sprintf("%s%v", cacheProjectsProjectCodePrefix, data.ProjectCode)
	projectsProjectIdKey := fmt.Sprintf("%s%v", cacheProjectsProjectIdPrefix, data.ProjectId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, projectsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.ProjectId, data.ProjectCode, data.UserId, data.Title, data.Description, data.Category, data.Status, data.Progress, data.Tags, data.LastActivityAt)
	}, projectsIdKey, projectsProjectCodeKey, projectsProjectIdKey)
	return ret, err
}

func (m *defaultProjectsModel) Update(ctx context.Context, newData *Projects) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	projectsIdKey := fmt.Sprintf("%s%v", cacheProjectsIdPrefix, data.Id)
	projectsProjectCodeKey := fmt.Sprintf("%s%v", cacheProjectsProjectCodePrefix, data.ProjectCode)
	projectsProjectIdKey := fmt.Sprintf("%s%v", cacheProjectsProjectIdPrefix, data.ProjectId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, projectsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeleteTime, newData.ProjectId, newData.ProjectCode, newData.UserId, newData.Title, newData.Description, newData.Category, newData.Status, newData.Progress, newData.Tags, newData.LastActivityAt, newData.Id)
	}, projectsIdKey, projectsProjectCodeKey, projectsProjectIdKey)
	return err
}

func (m *defaultProjectsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProjectsIdPrefix, primary)
}

func (m *defaultProjectsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", projectsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProjectsModel) tableName() string {
	return m.table
}
