// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.7

package hps

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	projectActivitiesFieldNames          = builder.RawFieldNames(&ProjectActivities{})
	projectActivitiesRows                = strings.Join(projectActivitiesFieldNames, ",")
	projectActivitiesRowsExpectAutoSet   = strings.Join(stringx.Remove(projectActivitiesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	projectActivitiesRowsWithPlaceHolder = strings.Join(stringx.Remove(projectActivitiesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheProjectActivitiesIdPrefix         = "cache:projectActivities:id:"
	cacheProjectActivitiesActivityIdPrefix = "cache:projectActivities:activityId:"
)

type (
	projectActivitiesModel interface {
		Insert(ctx context.Context, data *ProjectActivities) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ProjectActivities, error)
		FindOneByActivityId(ctx context.Context, activityId int64) (*ProjectActivities, error)
		Update(ctx context.Context, data *ProjectActivities) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProjectActivitiesModel struct {
		sqlc.CachedConn
		table string
	}

	ProjectActivities struct {
		Id          uint64         `db:"id"`          // 主键ID
		CreateTime  time.Time      `db:"create_time"` // 创建时间
		UpdateTime  time.Time      `db:"update_time"` // 更新时间
		DeleteTime  sql.NullTime   `db:"delete_time"` // 删除时间
		ActivityId  int64          `db:"activity_id"` // 活动ID
		ProjectId   int64          `db:"project_id"`  // 项目ID
		UserId      int64          `db:"user_id"`     // 用户ID
		Type        string         `db:"type"`        // 活动类型
		Description string         `db:"description"` // 活动描述
		Metadata    sql.NullString `db:"metadata"`    // 活动元数据JSON
		IpAddress   sql.NullString `db:"ip_address"`  // IP地址
		UserAgent   sql.NullString `db:"user_agent"`  // 用户代理
	}
)

func newProjectActivitiesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProjectActivitiesModel {
	return &defaultProjectActivitiesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`project_activities`",
	}
}

func (m *defaultProjectActivitiesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	projectActivitiesActivityIdKey := fmt.Sprintf("%s%v", cacheProjectActivitiesActivityIdPrefix, data.ActivityId)
	projectActivitiesIdKey := fmt.Sprintf("%s%v", cacheProjectActivitiesIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, projectActivitiesActivityIdKey, projectActivitiesIdKey)
	return err
}

func (m *defaultProjectActivitiesModel) FindOne(ctx context.Context, id uint64) (*ProjectActivities, error) {
	projectActivitiesIdKey := fmt.Sprintf("%s%v", cacheProjectActivitiesIdPrefix, id)
	var resp ProjectActivities
	err := m.QueryRowCtx(ctx, &resp, projectActivitiesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", projectActivitiesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProjectActivitiesModel) FindOneByActivityId(ctx context.Context, activityId int64) (*ProjectActivities, error) {
	projectActivitiesActivityIdKey := fmt.Sprintf("%s%v", cacheProjectActivitiesActivityIdPrefix, activityId)
	var resp ProjectActivities
	err := m.QueryRowIndexCtx(ctx, &resp, projectActivitiesActivityIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `activity_id` = ? limit 1", projectActivitiesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, activityId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProjectActivitiesModel) Insert(ctx context.Context, data *ProjectActivities) (sql.Result, error) {
	projectActivitiesActivityIdKey := fmt.Sprintf("%s%v", cacheProjectActivitiesActivityIdPrefix, data.ActivityId)
	projectActivitiesIdKey := fmt.Sprintf("%s%v", cacheProjectActivitiesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, projectActivitiesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.ActivityId, data.ProjectId, data.UserId, data.Type, data.Description, data.Metadata, data.IpAddress, data.UserAgent)
	}, projectActivitiesActivityIdKey, projectActivitiesIdKey)
	return ret, err
}

func (m *defaultProjectActivitiesModel) Update(ctx context.Context, newData *ProjectActivities) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	projectActivitiesActivityIdKey := fmt.Sprintf("%s%v", cacheProjectActivitiesActivityIdPrefix, data.ActivityId)
	projectActivitiesIdKey := fmt.Sprintf("%s%v", cacheProjectActivitiesIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, projectActivitiesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeleteTime, newData.ActivityId, newData.ProjectId, newData.UserId, newData.Type, newData.Description, newData.Metadata, newData.IpAddress, newData.UserAgent, newData.Id)
	}, projectActivitiesActivityIdKey, projectActivitiesIdKey)
	return err
}

func (m *defaultProjectActivitiesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProjectActivitiesIdPrefix, primary)
}

func (m *defaultProjectActivitiesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", projectActivitiesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProjectActivitiesModel) tableName() string {
	return m.table
}
