// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.7

package hps

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	questionsFieldNames          = builder.RawFieldNames(&Questions{})
	questionsRows                = strings.Join(questionsFieldNames, ",")
	questionsRowsExpectAutoSet   = strings.Join(stringx.Remove(questionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	questionsRowsWithPlaceHolder = strings.Join(stringx.Remove(questionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheQuestionsIdPrefix         = "cache:questions:id:"
	cacheQuestionsQuestionIdPrefix = "cache:questions:questionId:"
)

type (
	questionsModel interface {
		Insert(ctx context.Context, data *Questions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Questions, error)
		FindOneByQuestionId(ctx context.Context, questionId int64) (*Questions, error)
		Update(ctx context.Context, data *Questions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultQuestionsModel struct {
		sqlc.CachedConn
		table string
	}

	Questions struct {
		Id                uint64         `db:"id"`                  // 主键ID
		CreateTime        time.Time      `db:"create_time"`         // 创建时间
		UpdateTime        time.Time      `db:"update_time"`         // 更新时间
		DeleteTime        sql.NullTime   `db:"delete_time"`         // 删除时间
		QuestionId        int64          `db:"question_id"`         // 问题ID
		ProjectId         int64          `db:"project_id"`          // 项目ID
		UserId            int64          `db:"user_id"`             // 用户ID
		ObservationId     sql.NullInt64  `db:"observation_id"`      // 关联的观察记录ID
		Content           string         `db:"content"`             // 问题内容
		Type              string         `db:"type"`                // 问题类型：observation,reasoning,experiment,comparison
		Difficulty        string         `db:"difficulty"`          // 难度级别：basic,intermediate,advanced
		Purpose           sql.NullString `db:"purpose"`             // 问题目的
		Hints             sql.NullString `db:"hints"`               // 提示JSON数组
		ExpectedThinking  sql.NullString `db:"expected_thinking"`   // 期望的思考方向
		AiAnswer          sql.NullString `db:"ai_answer"`           // AI回答
		KeyPoints         sql.NullString `db:"key_points"`          // 关键要点JSON数组
		Examples          sql.NullString `db:"examples"`            // 举例说明JSON数组
		Analogies         sql.NullString `db:"analogies"`           // 类比JSON数组
		VisualAids        sql.NullString `db:"visual_aids"`         // 视觉辅助建议JSON数组
		FollowUpQuestions sql.NullString `db:"follow_up_questions"` // 后续问题建议JSON数组
		ThinkingPrompts   sql.NullString `db:"thinking_prompts"`    // 思考提示JSON数组
		Activities        sql.NullString `db:"activities"`          // 建议活动JSON数组
		UserResponse      sql.NullString `db:"user_response"`       // 用户回答
		ResponseTime      sql.NullTime   `db:"response_time"`       // 回答时间
	}
)

func newQuestionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultQuestionsModel {
	return &defaultQuestionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`questions`",
	}
}

func (m *defaultQuestionsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	questionsIdKey := fmt.Sprintf("%s%v", cacheQuestionsIdPrefix, id)
	questionsQuestionIdKey := fmt.Sprintf("%s%v", cacheQuestionsQuestionIdPrefix, data.QuestionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, questionsIdKey, questionsQuestionIdKey)
	return err
}

func (m *defaultQuestionsModel) FindOne(ctx context.Context, id uint64) (*Questions, error) {
	questionsIdKey := fmt.Sprintf("%s%v", cacheQuestionsIdPrefix, id)
	var resp Questions
	err := m.QueryRowCtx(ctx, &resp, questionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", questionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultQuestionsModel) FindOneByQuestionId(ctx context.Context, questionId int64) (*Questions, error) {
	questionsQuestionIdKey := fmt.Sprintf("%s%v", cacheQuestionsQuestionIdPrefix, questionId)
	var resp Questions
	err := m.QueryRowIndexCtx(ctx, &resp, questionsQuestionIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `question_id` = ? limit 1", questionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, questionId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultQuestionsModel) Insert(ctx context.Context, data *Questions) (sql.Result, error) {
	questionsIdKey := fmt.Sprintf("%s%v", cacheQuestionsIdPrefix, data.Id)
	questionsQuestionIdKey := fmt.Sprintf("%s%v", cacheQuestionsQuestionIdPrefix, data.QuestionId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, questionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.QuestionId, data.ProjectId, data.UserId, data.ObservationId, data.Content, data.Type, data.Difficulty, data.Purpose, data.Hints, data.ExpectedThinking, data.AiAnswer, data.KeyPoints, data.Examples, data.Analogies, data.VisualAids, data.FollowUpQuestions, data.ThinkingPrompts, data.Activities, data.UserResponse, data.ResponseTime)
	}, questionsIdKey, questionsQuestionIdKey)
	return ret, err
}

func (m *defaultQuestionsModel) Update(ctx context.Context, newData *Questions) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	questionsIdKey := fmt.Sprintf("%s%v", cacheQuestionsIdPrefix, data.Id)
	questionsQuestionIdKey := fmt.Sprintf("%s%v", cacheQuestionsQuestionIdPrefix, data.QuestionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, questionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeleteTime, newData.QuestionId, newData.ProjectId, newData.UserId, newData.ObservationId, newData.Content, newData.Type, newData.Difficulty, newData.Purpose, newData.Hints, newData.ExpectedThinking, newData.AiAnswer, newData.KeyPoints, newData.Examples, newData.Analogies, newData.VisualAids, newData.FollowUpQuestions, newData.ThinkingPrompts, newData.Activities, newData.UserResponse, newData.ResponseTime, newData.Id)
	}, questionsIdKey, questionsQuestionIdKey)
	return err
}

func (m *defaultQuestionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheQuestionsIdPrefix, primary)
}

func (m *defaultQuestionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", questionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultQuestionsModel) tableName() string {
	return m.table
}
