// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: audio-processing.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioProcessingService_SpeechToText_FullMethodName = "/audioprocessing.AudioProcessingService/SpeechToText"
	AudioProcessingService_TextToSpeech_FullMethodName = "/audioprocessing.AudioProcessingService/TextToSpeech"
)

// AudioProcessingServiceClient is the client API for AudioProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 语音处理服务
type AudioProcessingServiceClient interface {
	// 语音转文字
	SpeechToText(ctx context.Context, in *SpeechToTextReq, opts ...grpc.CallOption) (*SpeechToTextResp, error)
	// 文字转语音
	TextToSpeech(ctx context.Context, in *TextToSpeechReq, opts ...grpc.CallOption) (*TextToSpeechResp, error)
}

type audioProcessingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioProcessingServiceClient(cc grpc.ClientConnInterface) AudioProcessingServiceClient {
	return &audioProcessingServiceClient{cc}
}

func (c *audioProcessingServiceClient) SpeechToText(ctx context.Context, in *SpeechToTextReq, opts ...grpc.CallOption) (*SpeechToTextResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpeechToTextResp)
	err := c.cc.Invoke(ctx, AudioProcessingService_SpeechToText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioProcessingServiceClient) TextToSpeech(ctx context.Context, in *TextToSpeechReq, opts ...grpc.CallOption) (*TextToSpeechResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextToSpeechResp)
	err := c.cc.Invoke(ctx, AudioProcessingService_TextToSpeech_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioProcessingServiceServer is the server API for AudioProcessingService service.
// All implementations must embed UnimplementedAudioProcessingServiceServer
// for forward compatibility.
//
// 语音处理服务
type AudioProcessingServiceServer interface {
	// 语音转文字
	SpeechToText(context.Context, *SpeechToTextReq) (*SpeechToTextResp, error)
	// 文字转语音
	TextToSpeech(context.Context, *TextToSpeechReq) (*TextToSpeechResp, error)
	mustEmbedUnimplementedAudioProcessingServiceServer()
}

// UnimplementedAudioProcessingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioProcessingServiceServer struct{}

func (UnimplementedAudioProcessingServiceServer) SpeechToText(context.Context, *SpeechToTextReq) (*SpeechToTextResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SpeechToText not implemented")
}
func (UnimplementedAudioProcessingServiceServer) TextToSpeech(context.Context, *TextToSpeechReq) (*TextToSpeechResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TextToSpeech not implemented")
}
func (UnimplementedAudioProcessingServiceServer) mustEmbedUnimplementedAudioProcessingServiceServer() {
}
func (UnimplementedAudioProcessingServiceServer) testEmbeddedByValue() {}

// UnsafeAudioProcessingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioProcessingServiceServer will
// result in compilation errors.
type UnsafeAudioProcessingServiceServer interface {
	mustEmbedUnimplementedAudioProcessingServiceServer()
}

func RegisterAudioProcessingServiceServer(s grpc.ServiceRegistrar, srv AudioProcessingServiceServer) {
	// If the following call panics, it indicates UnimplementedAudioProcessingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioProcessingService_ServiceDesc, srv)
}

func _AudioProcessingService_SpeechToText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpeechToTextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioProcessingServiceServer).SpeechToText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioProcessingService_SpeechToText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioProcessingServiceServer).SpeechToText(ctx, req.(*SpeechToTextReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioProcessingService_TextToSpeech_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextToSpeechReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioProcessingServiceServer).TextToSpeech(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioProcessingService_TextToSpeech_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioProcessingServiceServer).TextToSpeech(ctx, req.(*TextToSpeechReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioProcessingService_ServiceDesc is the grpc.ServiceDesc for AudioProcessingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioProcessingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audioprocessing.AudioProcessingService",
	HandlerType: (*AudioProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpeechToText",
			Handler:    _AudioProcessingService_SpeechToText_Handler,
		},
		{
			MethodName: "TextToSpeech",
			Handler:    _AudioProcessingService_TextToSpeech_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audio-processing.proto",
}
