-- 创建用户表
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `username` varchar(50) DEFAULT NULL COMMENT '用户名',
  `nickname` varchar(100) DEFAULT NULL COMMENT '昵称',
  `avatar` varchar(500) DEFAULT NULL COMMENT '头像URL',
  `age` int(11) DEFAULT NULL COMMENT '年龄',
  `gender` varchar(10) DEFAULT NULL COMMENT '性别：male,female,other',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `status` varchar(20) NOT NULL DEFAULT 'active' COMMENT '状态：active,inactive',
  `last_login_at` datetime DEFAULT NULL COMMENT '最后登录时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_id` (`user_id`),
  KEY `idx_username` (`username`),
  KEY `idx_phone` (`phone`),
  KEY `idx_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

-- 创建项目表
CREATE TABLE IF NOT EXISTS `projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  `project_id` bigint(20) NOT NULL COMMENT '项目ID',
  `project_code` varchar(50) NOT NULL COMMENT '项目编码',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `title` varchar(200) NOT NULL COMMENT '项目标题',
  `description` text COMMENT '项目描述',
  `category` varchar(50) NOT NULL COMMENT '项目类别',
  `status` varchar(20) NOT NULL DEFAULT 'active' COMMENT '状态：active,completed,paused',
  `progress` int(11) NOT NULL DEFAULT '0' COMMENT '进度百分比(0-100)',
  `tags` text COMMENT '标签JSON数组',
  `last_activity_at` datetime DEFAULT NULL COMMENT '最后活动时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_project_id` (`project_id`),
  UNIQUE KEY `idx_project_code` (`project_code`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_category` (`category`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='探索项目表';

-- 创建观察记录表
CREATE TABLE IF NOT EXISTS `observations` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  `observation_id` bigint(20) NOT NULL COMMENT '观察记录ID',
  `project_id` bigint(20) NOT NULL COMMENT '项目ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `image_url` varchar(500) NOT NULL COMMENT '图片URL',
  `image_name` varchar(200) DEFAULT NULL COMMENT '图片名称',
  `image_type` varchar(10) DEFAULT NULL COMMENT '图片类型：jpeg,png,jpg',
  `image_size` bigint(20) DEFAULT NULL COMMENT '图片大小(字节)',
  `object_name` varchar(100) DEFAULT NULL COMMENT '识别对象名称',
  `category` varchar(50) DEFAULT NULL COMMENT '类别',
  `confidence` decimal(5,4) DEFAULT NULL COMMENT '置信度',
  `description` text COMMENT '描述',
  `key_features` text COMMENT '关键特征JSON数组',
  `scientific_name` varchar(100) DEFAULT NULL COMMENT '学名',
  `ar_info` text COMMENT 'AR信息JSON',
  `suggestions` text COMMENT 'AI建议JSON数组',
  `interesting_facts` text COMMENT '有趣事实JSON数组',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_observation_id` (`observation_id`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_object_name` (`object_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='观察记录表';

-- 创建问题记录表
CREATE TABLE IF NOT EXISTS `questions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  `question_id` bigint(20) NOT NULL COMMENT '问题ID',
  `project_id` bigint(20) NOT NULL COMMENT '项目ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `observation_id` bigint(20) DEFAULT NULL COMMENT '关联的观察记录ID',
  `content` text NOT NULL COMMENT '问题内容',
  `type` varchar(20) NOT NULL COMMENT '问题类型：observation,reasoning,experiment,comparison',
  `difficulty` varchar(20) DEFAULT 'basic' COMMENT '难度级别：basic,intermediate,advanced',
  `purpose` text COMMENT '问题目的',
  `hints` text COMMENT '提示JSON数组',
  `expected_thinking` text COMMENT '期望的思考方向',
  `ai_answer` text COMMENT 'AI回答',
  `key_points` text COMMENT '关键要点JSON数组',
  `examples` text COMMENT '举例说明JSON数组',
  `analogies` text COMMENT '类比JSON数组',
  `visual_aids` text COMMENT '视觉辅助建议JSON数组',
  `follow_up_questions` text COMMENT '后续问题建议JSON数组',
  `thinking_prompts` text COMMENT '思考提示JSON数组',
  `activities` text COMMENT '建议活动JSON数组',
  `user_response` text COMMENT '用户回答',
  `response_time` datetime DEFAULT NULL COMMENT '回答时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_question_id` (`question_id`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_observation_id` (`observation_id`),
  KEY `idx_type` (`type`),
  KEY `idx_difficulty` (`difficulty`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='问题记录表';

-- 创建表达记录表
CREATE TABLE IF NOT EXISTS `expressions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  `expression_id` bigint(20) NOT NULL COMMENT '表达记录ID',
  `project_id` bigint(20) NOT NULL COMMENT '项目ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `question_id` bigint(20) DEFAULT NULL COMMENT '关联的问题ID',
  `type` varchar(20) NOT NULL COMMENT '类型：speech,text,note',
  `raw_content` text NOT NULL COMMENT '原始内容',
  `language` varchar(10) DEFAULT 'zh-CN' COMMENT '语言代码',
  `audio_url` varchar(500) DEFAULT NULL COMMENT '音频URL',
  `audio_format` varchar(10) DEFAULT NULL COMMENT '音频格式：wav,mp3,m4a',
  `audio_size` bigint(20) DEFAULT NULL COMMENT '音频大小(字节)',
  `duration` decimal(10,2) DEFAULT NULL COMMENT '音频时长(秒)',
  `confidence` decimal(5,4) DEFAULT NULL COMMENT '识别置信度',
  `polished_title` varchar(200) DEFAULT NULL COMMENT '润色后的标题',
  `polished_summary` text COMMENT '内容总结',
  `polished_key_points` text COMMENT '关键要点JSON数组',
  `polished_concepts` text COMMENT '科学概念JSON数组',
  `polished_questions` text COMMENT '引发的疑问JSON数组',
  `polished_connections` text COMMENT '关联知识JSON数组',
  `polished_visuals` text COMMENT '视觉元素JSON数组',
  `polished_formatted` text COMMENT '格式化文本',
  `suggestions` text COMMENT '改进建议JSON数组',
  `key_learnings` text COMMENT '关键学习点JSON数组',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_expression_id` (`expression_id`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_question_id` (`question_id`),
  KEY `idx_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='表达记录表';

-- 创建成果记录表
CREATE TABLE IF NOT EXISTS `achievements` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  `achievement_id` bigint(20) NOT NULL COMMENT '成果ID',
  `project_id` bigint(20) NOT NULL COMMENT '项目ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `type` varchar(20) NOT NULL COMMENT '成果类型：report,documentary,poster',
  `title` varchar(200) NOT NULL COMMENT '成果标题',
  `description` text COMMENT '成果描述',
  `content` longtext NOT NULL COMMENT '成果内容JSON',
  `url` varchar(500) DEFAULT NULL COMMENT '成果URL',
  `file_size` bigint(20) DEFAULT NULL COMMENT '文件大小(字节)',
  `style` varchar(50) DEFAULT NULL COMMENT '风格参数',
  `layout` varchar(50) DEFAULT NULL COMMENT '布局参数',
  `length` varchar(20) DEFAULT NULL COMMENT '时长参数',
  `status` varchar(20) DEFAULT 'completed' COMMENT '状态：generating,completed,failed',
  `error_msg` text COMMENT '错误信息',
  `view_count` bigint(20) DEFAULT '0' COMMENT '查看次数',
  `like_count` bigint(20) DEFAULT '0' COMMENT '点赞次数',
  `share_count` bigint(20) DEFAULT '0' COMMENT '分享次数',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_achievement_id` (`achievement_id`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_type` (`type`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成果记录表';

-- 创建项目活动记录表
CREATE TABLE IF NOT EXISTS `project_activities` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  `activity_id` bigint(20) NOT NULL COMMENT '活动ID',
  `project_id` bigint(20) NOT NULL COMMENT '项目ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `type` varchar(50) NOT NULL COMMENT '活动类型',
  `description` text NOT NULL COMMENT '活动描述',
  `metadata` text COMMENT '活动元数据JSON',
  `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP地址',
  `user_agent` varchar(500) DEFAULT NULL COMMENT '用户代理',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_activity_id` (`activity_id`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_type` (`type`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目活动记录表';
