// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: video-processing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 视频分析请求
type AnalyzeVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoData     []byte                 `protobuf:"bytes,1,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"`          // 视频数据
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                                 // 视频格式，如 "mp4", "avi", "mov"
	AnalysisType  string                 `protobuf:"bytes,3,opt,name=analysis_type,json=analysisType,proto3" json:"analysis_type,omitempty"` // 分析类型: "content", "scene", "object", "emotion"
	Duration      float64                `protobuf:"fixed64,4,opt,name=duration,proto3" json:"duration,omitempty"`                           // 分析时长(秒)，0表示分析整个视频
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeVideoReq) Reset() {
	*x = AnalyzeVideoReq{}
	mi := &file_video_processing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeVideoReq) ProtoMessage() {}

func (x *AnalyzeVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeVideoReq.ProtoReflect.Descriptor instead.
func (*AnalyzeVideoReq) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeVideoReq) GetVideoData() []byte {
	if x != nil {
		return x.VideoData
	}
	return nil
}

func (x *AnalyzeVideoReq) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AnalyzeVideoReq) GetAnalysisType() string {
	if x != nil {
		return x.AnalysisType
	}
	return ""
}

func (x *AnalyzeVideoReq) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// 视频分析响应
type AnalyzeVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Result        *VideoAnalysisResult   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeVideoResp) Reset() {
	*x = AnalyzeVideoResp{}
	mi := &file_video_processing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeVideoResp) ProtoMessage() {}

func (x *AnalyzeVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeVideoResp.ProtoReflect.Descriptor instead.
func (*AnalyzeVideoResp) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeVideoResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AnalyzeVideoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AnalyzeVideoResp) GetResult() *VideoAnalysisResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// 视频分析结果
type VideoAnalysisResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenes        []*SceneAnalysis       `protobuf:"bytes,1,rep,name=scenes,proto3" json:"scenes,omitempty"`     // 场景分析结果
	Objects       []*ObjectDetection     `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`   // 物体检测结果
	Emotions      []*EmotionAnalysis     `protobuf:"bytes,3,rep,name=emotions,proto3" json:"emotions,omitempty"` // 情感分析结果
	Texts         []*TextRecognition     `protobuf:"bytes,4,rep,name=texts,proto3" json:"texts,omitempty"`       // 文字识别结果
	Audio         []*AudioAnalysis       `protobuf:"bytes,5,rep,name=audio,proto3" json:"audio,omitempty"`       // 音频分析结果
	Summary       *VideoSummary          `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`   // 视频总结
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoAnalysisResult) Reset() {
	*x = VideoAnalysisResult{}
	mi := &file_video_processing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoAnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoAnalysisResult) ProtoMessage() {}

func (x *VideoAnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoAnalysisResult.ProtoReflect.Descriptor instead.
func (*VideoAnalysisResult) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{2}
}

func (x *VideoAnalysisResult) GetScenes() []*SceneAnalysis {
	if x != nil {
		return x.Scenes
	}
	return nil
}

func (x *VideoAnalysisResult) GetObjects() []*ObjectDetection {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *VideoAnalysisResult) GetEmotions() []*EmotionAnalysis {
	if x != nil {
		return x.Emotions
	}
	return nil
}

func (x *VideoAnalysisResult) GetTexts() []*TextRecognition {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *VideoAnalysisResult) GetAudio() []*AudioAnalysis {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *VideoAnalysisResult) GetSummary() *VideoSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// 场景分析
type SceneAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     float64                `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                // 时间戳(秒)
	SceneType     string                 `protobuf:"bytes,2,opt,name=scene_type,json=sceneType,proto3" json:"scene_type,omitempty"` // 场景类型: "indoor", "outdoor", "nature", etc.
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`              // 置信度
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`              // 场景描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneAnalysis) Reset() {
	*x = SceneAnalysis{}
	mi := &file_video_processing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneAnalysis) ProtoMessage() {}

func (x *SceneAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneAnalysis.ProtoReflect.Descriptor instead.
func (*SceneAnalysis) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{3}
}

func (x *SceneAnalysis) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SceneAnalysis) GetSceneType() string {
	if x != nil {
		return x.SceneType
	}
	return ""
}

func (x *SceneAnalysis) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SceneAnalysis) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 物体检测
type ObjectDetection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     float64                `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                   // 时间戳(秒)
	ObjectName    string                 `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"` // 物体名称
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`                 // 置信度
	Bbox          *BoundingBox           `protobuf:"bytes,4,opt,name=bbox,proto3" json:"bbox,omitempty"`                               // 边界框
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectDetection) Reset() {
	*x = ObjectDetection{}
	mi := &file_video_processing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectDetection) ProtoMessage() {}

func (x *ObjectDetection) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectDetection.ProtoReflect.Descriptor instead.
func (*ObjectDetection) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectDetection) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ObjectDetection) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *ObjectDetection) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ObjectDetection) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

// 边界框
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`           // 左上角x坐标
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`           // 左上角y坐标
	Width         float64                `protobuf:"fixed64,3,opt,name=width,proto3" json:"width,omitempty"`   // 宽度
	Height        float64                `protobuf:"fixed64,4,opt,name=height,proto3" json:"height,omitempty"` // 高度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_video_processing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{5}
}

func (x *BoundingBox) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoundingBox) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoundingBox) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoundingBox) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// 情感分析
type EmotionAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     float64                `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`   // 时间戳(秒)
	Emotion       string                 `protobuf:"bytes,2,opt,name=emotion,proto3" json:"emotion,omitempty"`         // 情感类型: "happy", "sad", "angry", etc.
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"` // 置信度
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"` // 情感描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmotionAnalysis) Reset() {
	*x = EmotionAnalysis{}
	mi := &file_video_processing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionAnalysis) ProtoMessage() {}

func (x *EmotionAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionAnalysis.ProtoReflect.Descriptor instead.
func (*EmotionAnalysis) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{6}
}

func (x *EmotionAnalysis) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EmotionAnalysis) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *EmotionAnalysis) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *EmotionAnalysis) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 文字识别
type TextRecognition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     float64                `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`   // 时间戳(秒)
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`               // 识别出的文字
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`       // 语言
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"` // 置信度
	Bbox          *BoundingBox           `protobuf:"bytes,5,opt,name=bbox,proto3" json:"bbox,omitempty"`               // 文字位置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRecognition) Reset() {
	*x = TextRecognition{}
	mi := &file_video_processing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRecognition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRecognition) ProtoMessage() {}

func (x *TextRecognition) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRecognition.ProtoReflect.Descriptor instead.
func (*TextRecognition) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{7}
}

func (x *TextRecognition) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TextRecognition) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextRecognition) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TextRecognition) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TextRecognition) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

// 音频分析
type AudioAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     float64                `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`       // 时间戳(秒)
	Transcription string                 `protobuf:"bytes,2,opt,name=transcription,proto3" json:"transcription,omitempty"` // 语音转文字
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`           // 语言
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`     // 置信度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioAnalysis) Reset() {
	*x = AudioAnalysis{}
	mi := &file_video_processing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioAnalysis) ProtoMessage() {}

func (x *AudioAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioAnalysis.ProtoReflect.Descriptor instead.
func (*AudioAnalysis) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{8}
}

func (x *AudioAnalysis) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AudioAnalysis) GetTranscription() string {
	if x != nil {
		return x.Transcription
	}
	return ""
}

func (x *AudioAnalysis) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AudioAnalysis) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// 视频总结
type VideoSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`             // 视频标题
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // 视频描述
	Keywords      []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`       // 关键词
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`       // 视频类别
	Duration      float64                `protobuf:"fixed64,5,opt,name=duration,proto3" json:"duration,omitempty"`     // 视频总时长
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSummary) Reset() {
	*x = VideoSummary{}
	mi := &file_video_processing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSummary) ProtoMessage() {}

func (x *VideoSummary) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSummary.ProtoReflect.Descriptor instead.
func (*VideoSummary) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{9}
}

func (x *VideoSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoSummary) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *VideoSummary) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *VideoSummary) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// 视频生成请求
type GenerateVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`       // 视频脚本
	Style         string                 `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`         // 风格: "educational", "story", "animation"
	Duration      float64                `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"` // 期望时长(秒)
	Scenes        []string               `protobuf:"bytes,4,rep,name=scenes,proto3" json:"scenes,omitempty"`       // 场景描述
	Voice         string                 `protobuf:"bytes,5,opt,name=voice,proto3" json:"voice,omitempty"`         // 语音类型
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`   // 语言
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateVideoReq) Reset() {
	*x = GenerateVideoReq{}
	mi := &file_video_processing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateVideoReq) ProtoMessage() {}

func (x *GenerateVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateVideoReq.ProtoReflect.Descriptor instead.
func (*GenerateVideoReq) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateVideoReq) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *GenerateVideoReq) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *GenerateVideoReq) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *GenerateVideoReq) GetScenes() []string {
	if x != nil {
		return x.Scenes
	}
	return nil
}

func (x *GenerateVideoReq) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *GenerateVideoReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// 视频生成响应
type GenerateVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	VideoData     []byte                 `protobuf:"bytes,3,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"` // 生成的视频数据
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`                        // 视频格式
	Duration      float64                `protobuf:"fixed64,5,opt,name=duration,proto3" json:"duration,omitempty"`                  // 实际时长
	Metadata      *VideoMetadata         `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`                    // 视频元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateVideoResp) Reset() {
	*x = GenerateVideoResp{}
	mi := &file_video_processing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateVideoResp) ProtoMessage() {}

func (x *GenerateVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateVideoResp.ProtoReflect.Descriptor instead.
func (*GenerateVideoResp) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateVideoResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GenerateVideoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GenerateVideoResp) GetVideoData() []byte {
	if x != nil {
		return x.VideoData
	}
	return nil
}

func (x *GenerateVideoResp) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GenerateVideoResp) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *GenerateVideoResp) GetMetadata() *VideoMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 视频元数据
type VideoMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                      // 视频标题
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                          // 视频描述
	Scenes        []string               `protobuf:"bytes,3,rep,name=scenes,proto3" json:"scenes,omitempty"`                                    // 生成的场景列表
	AudioLanguage string                 `protobuf:"bytes,4,opt,name=audio_language,json=audioLanguage,proto3" json:"audio_language,omitempty"` // 音频语言
	Resolution    string                 `protobuf:"bytes,5,opt,name=resolution,proto3" json:"resolution,omitempty"`                            // 分辨率，如 "1920x1080"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoMetadata) Reset() {
	*x = VideoMetadata{}
	mi := &file_video_processing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMetadata) ProtoMessage() {}

func (x *VideoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_video_processing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMetadata.ProtoReflect.Descriptor instead.
func (*VideoMetadata) Descriptor() ([]byte, []int) {
	return file_video_processing_proto_rawDescGZIP(), []int{12}
}

func (x *VideoMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoMetadata) GetScenes() []string {
	if x != nil {
		return x.Scenes
	}
	return nil
}

func (x *VideoMetadata) GetAudioLanguage() string {
	if x != nil {
		return x.AudioLanguage
	}
	return ""
}

func (x *VideoMetadata) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

var File_video_processing_proto protoreflect.FileDescriptor

const file_video_processing_proto_rawDesc = "" +
	"\n" +
	"\x16video-processing.proto\x12\x0fvideoprocessing\"\x89\x01\n" +
	"\x0fAnalyzeVideoReq\x12\x1d\n" +
	"\n" +
	"video_data\x18\x01 \x01(\fR\tvideoData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12#\n" +
	"\ranalysis_type\x18\x03 \x01(\tR\fanalysisType\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x01R\bduration\"z\n" +
	"\x10AnalyzeVideoResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12<\n" +
	"\x06result\x18\x03 \x01(\v2$.videoprocessing.VideoAnalysisResultR\x06result\"\xee\x02\n" +
	"\x13VideoAnalysisResult\x126\n" +
	"\x06scenes\x18\x01 \x03(\v2\x1e.videoprocessing.SceneAnalysisR\x06scenes\x12:\n" +
	"\aobjects\x18\x02 \x03(\v2 .videoprocessing.ObjectDetectionR\aobjects\x12<\n" +
	"\bemotions\x18\x03 \x03(\v2 .videoprocessing.EmotionAnalysisR\bemotions\x126\n" +
	"\x05texts\x18\x04 \x03(\v2 .videoprocessing.TextRecognitionR\x05texts\x124\n" +
	"\x05audio\x18\x05 \x03(\v2\x1e.videoprocessing.AudioAnalysisR\x05audio\x127\n" +
	"\asummary\x18\x06 \x01(\v2\x1d.videoprocessing.VideoSummaryR\asummary\"\x8e\x01\n" +
	"\rSceneAnalysis\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\x12\x1d\n" +
	"\n" +
	"scene_type\x18\x02 \x01(\tR\tsceneType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xa2\x01\n" +
	"\x0fObjectDetection\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\x12\x1f\n" +
	"\vobject_name\x18\x02 \x01(\tR\n" +
	"objectName\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x120\n" +
	"\x04bbox\x18\x04 \x01(\v2\x1c.videoprocessing.BoundingBoxR\x04bbox\"W\n" +
	"\vBoundingBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x01R\x06height\"\x8b\x01\n" +
	"\x0fEmotionAnalysis\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\x12\x18\n" +
	"\aemotion\x18\x02 \x01(\tR\aemotion\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xb1\x01\n" +
	"\x0fTextRecognition\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x120\n" +
	"\x04bbox\x18\x05 \x01(\v2\x1c.videoprocessing.BoundingBoxR\x04bbox\"\x8f\x01\n" +
	"\rAudioAnalysis\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\x12$\n" +
	"\rtranscription\x18\x02 \x01(\tR\rtranscription\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\"\x9a\x01\n" +
	"\fVideoSummary\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x01R\bduration\"\xa6\x01\n" +
	"\x10GenerateVideoReq\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x14\n" +
	"\x05style\x18\x02 \x01(\tR\x05style\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x01R\bduration\x12\x16\n" +
	"\x06scenes\x18\x04 \x03(\tR\x06scenes\x12\x14\n" +
	"\x05voice\x18\x05 \x01(\tR\x05voice\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\"\xcc\x01\n" +
	"\x11GenerateVideoResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1d\n" +
	"\n" +
	"video_data\x18\x03 \x01(\fR\tvideoData\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x01R\bduration\x12:\n" +
	"\bmetadata\x18\x06 \x01(\v2\x1e.videoprocessing.VideoMetadataR\bmetadata\"\xa6\x01\n" +
	"\rVideoMetadata\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06scenes\x18\x03 \x03(\tR\x06scenes\x12%\n" +
	"\x0eaudio_language\x18\x04 \x01(\tR\raudioLanguage\x12\x1e\n" +
	"\n" +
	"resolution\x18\x05 \x01(\tR\n" +
	"resolution2\xc5\x01\n" +
	"\x16VideoProcessingService\x12S\n" +
	"\fAnalyzeVideo\x12 .videoprocessing.AnalyzeVideoReq\x1a!.videoprocessing.AnalyzeVideoResp\x12V\n" +
	"\rGenerateVideo\x12!.videoprocessing.GenerateVideoReq\x1a\".videoprocessing.GenerateVideoRespB'Z%explorapal/app/video-processing/protob\x06proto3"

var (
	file_video_processing_proto_rawDescOnce sync.Once
	file_video_processing_proto_rawDescData []byte
)

func file_video_processing_proto_rawDescGZIP() []byte {
	file_video_processing_proto_rawDescOnce.Do(func() {
		file_video_processing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_processing_proto_rawDesc), len(file_video_processing_proto_rawDesc)))
	})
	return file_video_processing_proto_rawDescData
}

var file_video_processing_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_video_processing_proto_goTypes = []any{
	(*AnalyzeVideoReq)(nil),     // 0: videoprocessing.AnalyzeVideoReq
	(*AnalyzeVideoResp)(nil),    // 1: videoprocessing.AnalyzeVideoResp
	(*VideoAnalysisResult)(nil), // 2: videoprocessing.VideoAnalysisResult
	(*SceneAnalysis)(nil),       // 3: videoprocessing.SceneAnalysis
	(*ObjectDetection)(nil),     // 4: videoprocessing.ObjectDetection
	(*BoundingBox)(nil),         // 5: videoprocessing.BoundingBox
	(*EmotionAnalysis)(nil),     // 6: videoprocessing.EmotionAnalysis
	(*TextRecognition)(nil),     // 7: videoprocessing.TextRecognition
	(*AudioAnalysis)(nil),       // 8: videoprocessing.AudioAnalysis
	(*VideoSummary)(nil),        // 9: videoprocessing.VideoSummary
	(*GenerateVideoReq)(nil),    // 10: videoprocessing.GenerateVideoReq
	(*GenerateVideoResp)(nil),   // 11: videoprocessing.GenerateVideoResp
	(*VideoMetadata)(nil),       // 12: videoprocessing.VideoMetadata
}
var file_video_processing_proto_depIdxs = []int32{
	2,  // 0: videoprocessing.AnalyzeVideoResp.result:type_name -> videoprocessing.VideoAnalysisResult
	3,  // 1: videoprocessing.VideoAnalysisResult.scenes:type_name -> videoprocessing.SceneAnalysis
	4,  // 2: videoprocessing.VideoAnalysisResult.objects:type_name -> videoprocessing.ObjectDetection
	6,  // 3: videoprocessing.VideoAnalysisResult.emotions:type_name -> videoprocessing.EmotionAnalysis
	7,  // 4: videoprocessing.VideoAnalysisResult.texts:type_name -> videoprocessing.TextRecognition
	8,  // 5: videoprocessing.VideoAnalysisResult.audio:type_name -> videoprocessing.AudioAnalysis
	9,  // 6: videoprocessing.VideoAnalysisResult.summary:type_name -> videoprocessing.VideoSummary
	5,  // 7: videoprocessing.ObjectDetection.bbox:type_name -> videoprocessing.BoundingBox
	5,  // 8: videoprocessing.TextRecognition.bbox:type_name -> videoprocessing.BoundingBox
	12, // 9: videoprocessing.GenerateVideoResp.metadata:type_name -> videoprocessing.VideoMetadata
	0,  // 10: videoprocessing.VideoProcessingService.AnalyzeVideo:input_type -> videoprocessing.AnalyzeVideoReq
	10, // 11: videoprocessing.VideoProcessingService.GenerateVideo:input_type -> videoprocessing.GenerateVideoReq
	1,  // 12: videoprocessing.VideoProcessingService.AnalyzeVideo:output_type -> videoprocessing.AnalyzeVideoResp
	11, // 13: videoprocessing.VideoProcessingService.GenerateVideo:output_type -> videoprocessing.GenerateVideoResp
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_video_processing_proto_init() }
func file_video_processing_proto_init() {
	if File_video_processing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_processing_proto_rawDesc), len(file_video_processing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_processing_proto_goTypes,
		DependencyIndexes: file_video_processing_proto_depIdxs,
		MessageInfos:      file_video_processing_proto_msgTypes,
	}.Build()
	File_video_processing_proto = out.File
	file_video_processing_proto_goTypes = nil
	file_video_processing_proto_depIdxs = nil
}
