// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: video-processing.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoProcessingService_AnalyzeVideo_FullMethodName  = "/videoprocessing.VideoProcessingService/AnalyzeVideo"
	VideoProcessingService_GenerateVideo_FullMethodName = "/videoprocessing.VideoProcessingService/GenerateVideo"
)

// VideoProcessingServiceClient is the client API for VideoProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 视频处理服务
type VideoProcessingServiceClient interface {
	// 视频分析
	AnalyzeVideo(ctx context.Context, in *AnalyzeVideoReq, opts ...grpc.CallOption) (*AnalyzeVideoResp, error)
	// 视频生成
	GenerateVideo(ctx context.Context, in *GenerateVideoReq, opts ...grpc.CallOption) (*GenerateVideoResp, error)
}

type videoProcessingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoProcessingServiceClient(cc grpc.ClientConnInterface) VideoProcessingServiceClient {
	return &videoProcessingServiceClient{cc}
}

func (c *videoProcessingServiceClient) AnalyzeVideo(ctx context.Context, in *AnalyzeVideoReq, opts ...grpc.CallOption) (*AnalyzeVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeVideoResp)
	err := c.cc.Invoke(ctx, VideoProcessingService_AnalyzeVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoProcessingServiceClient) GenerateVideo(ctx context.Context, in *GenerateVideoReq, opts ...grpc.CallOption) (*GenerateVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateVideoResp)
	err := c.cc.Invoke(ctx, VideoProcessingService_GenerateVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoProcessingServiceServer is the server API for VideoProcessingService service.
// All implementations must embed UnimplementedVideoProcessingServiceServer
// for forward compatibility.
//
// 视频处理服务
type VideoProcessingServiceServer interface {
	// 视频分析
	AnalyzeVideo(context.Context, *AnalyzeVideoReq) (*AnalyzeVideoResp, error)
	// 视频生成
	GenerateVideo(context.Context, *GenerateVideoReq) (*GenerateVideoResp, error)
	mustEmbedUnimplementedVideoProcessingServiceServer()
}

// UnimplementedVideoProcessingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoProcessingServiceServer struct{}

func (UnimplementedVideoProcessingServiceServer) AnalyzeVideo(context.Context, *AnalyzeVideoReq) (*AnalyzeVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeVideo not implemented")
}
func (UnimplementedVideoProcessingServiceServer) GenerateVideo(context.Context, *GenerateVideoReq) (*GenerateVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateVideo not implemented")
}
func (UnimplementedVideoProcessingServiceServer) mustEmbedUnimplementedVideoProcessingServiceServer() {
}
func (UnimplementedVideoProcessingServiceServer) testEmbeddedByValue() {}

// UnsafeVideoProcessingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoProcessingServiceServer will
// result in compilation errors.
type UnsafeVideoProcessingServiceServer interface {
	mustEmbedUnimplementedVideoProcessingServiceServer()
}

func RegisterVideoProcessingServiceServer(s grpc.ServiceRegistrar, srv VideoProcessingServiceServer) {
	// If the following call panics, it indicates UnimplementedVideoProcessingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoProcessingService_ServiceDesc, srv)
}

func _VideoProcessingService_AnalyzeVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoProcessingServiceServer).AnalyzeVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoProcessingService_AnalyzeVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoProcessingServiceServer).AnalyzeVideo(ctx, req.(*AnalyzeVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoProcessingService_GenerateVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoProcessingServiceServer).GenerateVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoProcessingService_GenerateVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoProcessingServiceServer).GenerateVideo(ctx, req.(*GenerateVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoProcessingService_ServiceDesc is the grpc.ServiceDesc for VideoProcessingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoProcessingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "videoprocessing.VideoProcessingService",
	HandlerType: (*VideoProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeVideo",
			Handler:    _VideoProcessingService_AnalyzeVideo_Handler,
		},
		{
			MethodName: "GenerateVideo",
			Handler:    _VideoProcessingService_GenerateVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video-processing.proto",
}
