// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: ai-dialogue.proto

package aidialogue

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AIDialogueService_AnalyzeImage_FullMethodName      = "/aidialogue.AIDialogueService/AnalyzeImage"
	AIDialogueService_GenerateQuestions_FullMethodName = "/aidialogue.AIDialogueService/GenerateQuestions"
	AIDialogueService_PolishNote_FullMethodName        = "/aidialogue.AIDialogueService/PolishNote"
	AIDialogueService_GenerateReport_FullMethodName    = "/aidialogue.AIDialogueService/GenerateReport"
)

// AIDialogueServiceClient is the client API for AIDialogueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIDialogueServiceClient interface {
	AnalyzeImage(ctx context.Context, in *AnalyzeImageReq, opts ...grpc.CallOption) (*AnalyzeImageResp, error)
	GenerateQuestions(ctx context.Context, in *GenerateQuestionsReq, opts ...grpc.CallOption) (*GenerateQuestionsResp, error)
	PolishNote(ctx context.Context, in *PolishNoteReq, opts ...grpc.CallOption) (*PolishNoteResp, error)
	GenerateReport(ctx context.Context, in *GenerateReportReq, opts ...grpc.CallOption) (*GenerateReportResp, error)
}

type aIDialogueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIDialogueServiceClient(cc grpc.ClientConnInterface) AIDialogueServiceClient {
	return &aIDialogueServiceClient{cc}
}

func (c *aIDialogueServiceClient) AnalyzeImage(ctx context.Context, in *AnalyzeImageReq, opts ...grpc.CallOption) (*AnalyzeImageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeImageResp)
	err := c.cc.Invoke(ctx, AIDialogueService_AnalyzeImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIDialogueServiceClient) GenerateQuestions(ctx context.Context, in *GenerateQuestionsReq, opts ...grpc.CallOption) (*GenerateQuestionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateQuestionsResp)
	err := c.cc.Invoke(ctx, AIDialogueService_GenerateQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIDialogueServiceClient) PolishNote(ctx context.Context, in *PolishNoteReq, opts ...grpc.CallOption) (*PolishNoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolishNoteResp)
	err := c.cc.Invoke(ctx, AIDialogueService_PolishNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIDialogueServiceClient) GenerateReport(ctx context.Context, in *GenerateReportReq, opts ...grpc.CallOption) (*GenerateReportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateReportResp)
	err := c.cc.Invoke(ctx, AIDialogueService_GenerateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIDialogueServiceServer is the server API for AIDialogueService service.
// All implementations must embed UnimplementedAIDialogueServiceServer
// for forward compatibility.
type AIDialogueServiceServer interface {
	AnalyzeImage(context.Context, *AnalyzeImageReq) (*AnalyzeImageResp, error)
	GenerateQuestions(context.Context, *GenerateQuestionsReq) (*GenerateQuestionsResp, error)
	PolishNote(context.Context, *PolishNoteReq) (*PolishNoteResp, error)
	GenerateReport(context.Context, *GenerateReportReq) (*GenerateReportResp, error)
	mustEmbedUnimplementedAIDialogueServiceServer()
}

// UnimplementedAIDialogueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIDialogueServiceServer struct{}

func (UnimplementedAIDialogueServiceServer) AnalyzeImage(context.Context, *AnalyzeImageReq) (*AnalyzeImageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeImage not implemented")
}
func (UnimplementedAIDialogueServiceServer) GenerateQuestions(context.Context, *GenerateQuestionsReq) (*GenerateQuestionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateQuestions not implemented")
}
func (UnimplementedAIDialogueServiceServer) PolishNote(context.Context, *PolishNoteReq) (*PolishNoteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PolishNote not implemented")
}
func (UnimplementedAIDialogueServiceServer) GenerateReport(context.Context, *GenerateReportReq) (*GenerateReportResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateReport not implemented")
}
func (UnimplementedAIDialogueServiceServer) mustEmbedUnimplementedAIDialogueServiceServer() {}
func (UnimplementedAIDialogueServiceServer) testEmbeddedByValue()                           {}

// UnsafeAIDialogueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIDialogueServiceServer will
// result in compilation errors.
type UnsafeAIDialogueServiceServer interface {
	mustEmbedUnimplementedAIDialogueServiceServer()
}

func RegisterAIDialogueServiceServer(s grpc.ServiceRegistrar, srv AIDialogueServiceServer) {
	// If the following call panics, it indicates UnimplementedAIDialogueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIDialogueService_ServiceDesc, srv)
}

func _AIDialogueService_AnalyzeImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeImageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIDialogueServiceServer).AnalyzeImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIDialogueService_AnalyzeImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIDialogueServiceServer).AnalyzeImage(ctx, req.(*AnalyzeImageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIDialogueService_GenerateQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQuestionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIDialogueServiceServer).GenerateQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIDialogueService_GenerateQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIDialogueServiceServer).GenerateQuestions(ctx, req.(*GenerateQuestionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIDialogueService_PolishNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolishNoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIDialogueServiceServer).PolishNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIDialogueService_PolishNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIDialogueServiceServer).PolishNote(ctx, req.(*PolishNoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIDialogueService_GenerateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIDialogueServiceServer).GenerateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIDialogueService_GenerateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIDialogueServiceServer).GenerateReport(ctx, req.(*GenerateReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AIDialogueService_ServiceDesc is the grpc.ServiceDesc for AIDialogueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIDialogueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aidialogue.AIDialogueService",
	HandlerType: (*AIDialogueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeImage",
			Handler:    _AIDialogueService_AnalyzeImage_Handler,
		},
		{
			MethodName: "GenerateQuestions",
			Handler:    _AIDialogueService_GenerateQuestions_Handler,
		},
		{
			MethodName: "PolishNote",
			Handler:    _AIDialogueService_PolishNote_Handler,
		},
		{
			MethodName: "GenerateReport",
			Handler:    _AIDialogueService_GenerateReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai-dialogue.proto",
}
