// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: ai-dialogue.proto

package aidialogue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeImageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeImageReq) Reset() {
	*x = AnalyzeImageReq{}
	mi := &file_ai_dialogue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeImageReq) ProtoMessage() {}

func (x *AnalyzeImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_dialogue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeImageReq.ProtoReflect.Descriptor instead.
func (*AnalyzeImageReq) Descriptor() ([]byte, []int) {
	return file_ai_dialogue_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeImageReq) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *AnalyzeImageReq) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AnalyzeImageReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type AnalyzeImageResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ObjectName     string                 `protobuf:"bytes,3,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	Category       string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Confidence     float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	KeyFeatures    []string               `protobuf:"bytes,7,rep,name=key_features,json=keyFeatures,proto3" json:"key_features,omitempty"`
	ScientificName string                 `protobuf:"bytes,8,opt,name=scientific_name,json=scientificName,proto3" json:"scientific_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeImageResp) Reset() {
	*x = AnalyzeImageResp{}
	mi := &file_ai_dialogue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeImageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeImageResp) ProtoMessage() {}

func (x *AnalyzeImageResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_dialogue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeImageResp.ProtoReflect.Descriptor instead.
func (*AnalyzeImageResp) Descriptor() ([]byte, []int) {
	return file_ai_dialogue_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeImageResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AnalyzeImageResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AnalyzeImageResp) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *AnalyzeImageResp) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AnalyzeImageResp) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalyzeImageResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnalyzeImageResp) GetKeyFeatures() []string {
	if x != nil {
		return x.KeyFeatures
	}
	return nil
}

func (x *AnalyzeImageResp) GetScientificName() string {
	if x != nil {
		return x.ScientificName
	}
	return ""
}

type GenerateQuestionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextInfo   string                 `protobuf:"bytes,1,opt,name=context_info,json=contextInfo,proto3" json:"context_info,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	UserAge       int64                  `protobuf:"varint,3,opt,name=user_age,json=userAge,proto3" json:"user_age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionsReq) Reset() {
	*x = GenerateQuestionsReq{}
	mi := &file_ai_dialogue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionsReq) ProtoMessage() {}

func (x *GenerateQuestionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_dialogue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionsReq.ProtoReflect.Descriptor instead.
func (*GenerateQuestionsReq) Descriptor() ([]byte, []int) {
	return file_ai_dialogue_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateQuestionsReq) GetContextInfo() string {
	if x != nil {
		return x.ContextInfo
	}
	return ""
}

func (x *GenerateQuestionsReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GenerateQuestionsReq) GetUserAge() int64 {
	if x != nil {
		return x.UserAge
	}
	return 0
}

type GenerateQuestionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Questions     []*Question            `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionsResp) Reset() {
	*x = GenerateQuestionsResp{}
	mi := &file_ai_dialogue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionsResp) ProtoMessage() {}

func (x *GenerateQuestionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_dialogue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionsResp.ProtoReflect.Descriptor instead.
func (*GenerateQuestionsResp) Descriptor() ([]byte, []int) {
	return file_ai_dialogue_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateQuestionsResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GenerateQuestionsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GenerateQuestionsResp) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Purpose       string                 `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_ai_dialogue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_ai_dialogue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_ai_dialogue_proto_rawDescGZIP(), []int{4}
}

func (x *Question) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Question) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Question) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Question) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type PolishNoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawContent    string                 `protobuf:"bytes,1,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	ContextInfo   string                 `protobuf:"bytes,2,opt,name=context_info,json=contextInfo,proto3" json:"context_info,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	UserAge       int64                  `protobuf:"varint,4,opt,name=user_age,json=userAge,proto3" json:"user_age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolishNoteReq) Reset() {
	*x = PolishNoteReq{}
	mi := &file_ai_dialogue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolishNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolishNoteReq) ProtoMessage() {}

func (x *PolishNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_dialogue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolishNoteReq.ProtoReflect.Descriptor instead.
func (*PolishNoteReq) Descriptor() ([]byte, []int) {
	return file_ai_dialogue_proto_rawDescGZIP(), []int{5}
}

func (x *PolishNoteReq) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *PolishNoteReq) GetContextInfo() string {
	if x != nil {
		return x.ContextInfo
	}
	return ""
}

func (x *PolishNoteReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PolishNoteReq) GetUserAge() int64 {
	if x != nil {
		return x.UserAge
	}
	return 0
}

type PolishNoteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	KeyPoints     []string               `protobuf:"bytes,5,rep,name=key_points,json=keyPoints,proto3" json:"key_points,omitempty"`
	FormattedText string                 `protobuf:"bytes,6,opt,name=formatted_text,json=formattedText,proto3" json:"formatted_text,omitempty"`
	Suggestions   []string               `protobuf:"bytes,7,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolishNoteResp) Reset() {
	*x = PolishNoteResp{}
	mi := &file_ai_dialogue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolishNoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolishNoteResp) ProtoMessage() {}

func (x *PolishNoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_dialogue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolishNoteResp.ProtoReflect.Descriptor instead.
func (*PolishNoteResp) Descriptor() ([]byte, []int) {
	return file_ai_dialogue_proto_rawDescGZIP(), []int{6}
}

func (x *PolishNoteResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PolishNoteResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PolishNoteResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PolishNoteResp) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PolishNoteResp) GetKeyPoints() []string {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *PolishNoteResp) GetFormattedText() string {
	if x != nil {
		return x.FormattedText
	}
	return ""
}

func (x *PolishNoteResp) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type GenerateReportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectData   string                 `protobuf:"bytes,1,opt,name=project_data,json=projectData,proto3" json:"project_data,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportReq) Reset() {
	*x = GenerateReportReq{}
	mi := &file_ai_dialogue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportReq) ProtoMessage() {}

func (x *GenerateReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_dialogue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportReq.ProtoReflect.Descriptor instead.
func (*GenerateReportReq) Descriptor() ([]byte, []int) {
	return file_ai_dialogue_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateReportReq) GetProjectData() string {
	if x != nil {
		return x.ProjectData
	}
	return ""
}

func (x *GenerateReportReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GenerateReportResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Abstract      string                 `protobuf:"bytes,5,opt,name=abstract,proto3" json:"abstract,omitempty"`
	Conclusion    string                 `protobuf:"bytes,6,opt,name=conclusion,proto3" json:"conclusion,omitempty"`
	NextSteps     []string               `protobuf:"bytes,7,rep,name=next_steps,json=nextSteps,proto3" json:"next_steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportResp) Reset() {
	*x = GenerateReportResp{}
	mi := &file_ai_dialogue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportResp) ProtoMessage() {}

func (x *GenerateReportResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_dialogue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportResp.ProtoReflect.Descriptor instead.
func (*GenerateReportResp) Descriptor() ([]byte, []int) {
	return file_ai_dialogue_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateReportResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GenerateReportResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GenerateReportResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GenerateReportResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GenerateReportResp) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

func (x *GenerateReportResp) GetConclusion() string {
	if x != nil {
		return x.Conclusion
	}
	return ""
}

func (x *GenerateReportResp) GetNextSteps() []string {
	if x != nil {
		return x.NextSteps
	}
	return nil
}

var File_ai_dialogue_proto protoreflect.FileDescriptor

const file_ai_dialogue_proto_rawDesc = "" +
	"\n" +
	"\x11ai-dialogue.proto\x12\n" +
	"aidialogue\"b\n" +
	"\x0fAnalyzeImageReq\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"\x87\x02\n" +
	"\x10AnalyzeImageResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\vobject_name\x18\x03 \x01(\tR\n" +
	"objectName\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12!\n" +
	"\fkey_features\x18\a \x03(\tR\vkeyFeatures\x12'\n" +
	"\x0fscientific_name\x18\b \x01(\tR\x0escientificName\"p\n" +
	"\x14GenerateQuestionsReq\x12!\n" +
	"\fcontext_info\x18\x01 \x01(\tR\vcontextInfo\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x19\n" +
	"\buser_age\x18\x03 \x01(\x03R\auserAge\"u\n" +
	"\x15GenerateQuestionsResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x122\n" +
	"\tquestions\x18\x03 \x03(\v2\x14.aidialogue.QuestionR\tquestions\"r\n" +
	"\bQuestion\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x18\n" +
	"\apurpose\x18\x04 \x01(\tR\apurpose\"\x8a\x01\n" +
	"\rPolishNoteReq\x12\x1f\n" +
	"\vraw_content\x18\x01 \x01(\tR\n" +
	"rawContent\x12!\n" +
	"\fcontext_info\x18\x02 \x01(\tR\vcontextInfo\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x19\n" +
	"\buser_age\x18\x04 \x01(\x03R\auserAge\"\xd2\x01\n" +
	"\x0ePolishNoteResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"key_points\x18\x05 \x03(\tR\tkeyPoints\x12%\n" +
	"\x0eformatted_text\x18\x06 \x01(\tR\rformattedText\x12 \n" +
	"\vsuggestions\x18\a \x03(\tR\vsuggestions\"R\n" +
	"\x11GenerateReportReq\x12!\n" +
	"\fproject_data\x18\x01 \x01(\tR\vprojectData\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"\xc9\x01\n" +
	"\x12GenerateReportResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\babstract\x18\x05 \x01(\tR\babstract\x12\x1e\n" +
	"\n" +
	"conclusion\x18\x06 \x01(\tR\n" +
	"conclusion\x12\x1d\n" +
	"\n" +
	"next_steps\x18\a \x03(\tR\tnextSteps2\xce\x02\n" +
	"\x11AIDialogueService\x12I\n" +
	"\fAnalyzeImage\x12\x1b.aidialogue.AnalyzeImageReq\x1a\x1c.aidialogue.AnalyzeImageResp\x12X\n" +
	"\x11GenerateQuestions\x12 .aidialogue.GenerateQuestionsReq\x1a!.aidialogue.GenerateQuestionsResp\x12C\n" +
	"\n" +
	"PolishNote\x12\x19.aidialogue.PolishNoteReq\x1a\x1a.aidialogue.PolishNoteResp\x12O\n" +
	"\x0eGenerateReport\x12\x1d.aidialogue.GenerateReportReq\x1a\x1e.aidialogue.GenerateReportRespB\x0eZ\f./aidialogueb\x06proto3"

var (
	file_ai_dialogue_proto_rawDescOnce sync.Once
	file_ai_dialogue_proto_rawDescData []byte
)

func file_ai_dialogue_proto_rawDescGZIP() []byte {
	file_ai_dialogue_proto_rawDescOnce.Do(func() {
		file_ai_dialogue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_dialogue_proto_rawDesc), len(file_ai_dialogue_proto_rawDesc)))
	})
	return file_ai_dialogue_proto_rawDescData
}

var file_ai_dialogue_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ai_dialogue_proto_goTypes = []any{
	(*AnalyzeImageReq)(nil),       // 0: aidialogue.AnalyzeImageReq
	(*AnalyzeImageResp)(nil),      // 1: aidialogue.AnalyzeImageResp
	(*GenerateQuestionsReq)(nil),  // 2: aidialogue.GenerateQuestionsReq
	(*GenerateQuestionsResp)(nil), // 3: aidialogue.GenerateQuestionsResp
	(*Question)(nil),              // 4: aidialogue.Question
	(*PolishNoteReq)(nil),         // 5: aidialogue.PolishNoteReq
	(*PolishNoteResp)(nil),        // 6: aidialogue.PolishNoteResp
	(*GenerateReportReq)(nil),     // 7: aidialogue.GenerateReportReq
	(*GenerateReportResp)(nil),    // 8: aidialogue.GenerateReportResp
}
var file_ai_dialogue_proto_depIdxs = []int32{
	4, // 0: aidialogue.GenerateQuestionsResp.questions:type_name -> aidialogue.Question
	0, // 1: aidialogue.AIDialogueService.AnalyzeImage:input_type -> aidialogue.AnalyzeImageReq
	2, // 2: aidialogue.AIDialogueService.GenerateQuestions:input_type -> aidialogue.GenerateQuestionsReq
	5, // 3: aidialogue.AIDialogueService.PolishNote:input_type -> aidialogue.PolishNoteReq
	7, // 4: aidialogue.AIDialogueService.GenerateReport:input_type -> aidialogue.GenerateReportReq
	1, // 5: aidialogue.AIDialogueService.AnalyzeImage:output_type -> aidialogue.AnalyzeImageResp
	3, // 6: aidialogue.AIDialogueService.GenerateQuestions:output_type -> aidialogue.GenerateQuestionsResp
	6, // 7: aidialogue.AIDialogueService.PolishNote:output_type -> aidialogue.PolishNoteResp
	8, // 8: aidialogue.AIDialogueService.GenerateReport:output_type -> aidialogue.GenerateReportResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_dialogue_proto_init() }
func file_ai_dialogue_proto_init() {
	if File_ai_dialogue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_dialogue_proto_rawDesc), len(file_ai_dialogue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_dialogue_proto_goTypes,
		DependencyIndexes: file_ai_dialogue_proto_depIdxs,
		MessageInfos:      file_ai_dialogue_proto_msgTypes,
	}.Build()
	File_ai_dialogue_proto = out.File
	file_ai_dialogue_proto_msgTypes = nil
	file_ai_dialogue_proto_depIdxs = nil
}
