// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.7
// Source: project-management.proto

package server

import (
	"context"

	"explorapal/app/project-management/rpc/internal/logic"
	"explorapal/app/project-management/rpc/internal/svc"
	"explorapal/app/project-management/rpc/projectmanagement"
)

type ProjectManagementServiceServer struct {
	svcCtx *svc.ServiceContext
	projectmanagement.UnimplementedProjectManagementServiceServer
}

func NewProjectManagementServiceServer(svcCtx *svc.ServiceContext) *ProjectManagementServiceServer {
	return &ProjectManagementServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ProjectManagementServiceServer) CreateProject(ctx context.Context, in *projectmanagement.CreateProjectReq) (*projectmanagement.CreateProjectResp, error) {
	l := logic.NewCreateProjectLogic(ctx, s.svcCtx)
	return l.CreateProject(in)
}

func (s *ProjectManagementServiceServer) GetProjectList(ctx context.Context, in *projectmanagement.GetProjectListReq) (*projectmanagement.GetProjectListResp, error) {
	l := logic.NewGetProjectListLogic(ctx, s.svcCtx)
	return l.GetProjectList(in)
}

func (s *ProjectManagementServiceServer) GetProjectDetail(ctx context.Context, in *projectmanagement.GetProjectDetailReq) (*projectmanagement.GetProjectDetailResp, error) {
	l := logic.NewGetProjectDetailLogic(ctx, s.svcCtx)
	return l.GetProjectDetail(in)
}

func (s *ProjectManagementServiceServer) UpdateProjectStatus(ctx context.Context, in *projectmanagement.UpdateProjectStatusReq) (*projectmanagement.UpdateProjectStatusResp, error) {
	l := logic.NewUpdateProjectStatusLogic(ctx, s.svcCtx)
	return l.UpdateProjectStatus(in)
}
