// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: audio-processing.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 语音转文字请求
type SpeechToTextReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"` // 音频数据
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                        // 音频格式，如 "wav", "mp3", "ogg"
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`                    // 语言代码，如 "zh-CN", "en-US"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeechToTextReq) Reset() {
	*x = SpeechToTextReq{}
	mi := &file_audio_processing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeechToTextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeechToTextReq) ProtoMessage() {}

func (x *SpeechToTextReq) ProtoReflect() protoreflect.Message {
	mi := &file_audio_processing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeechToTextReq.ProtoReflect.Descriptor instead.
func (*SpeechToTextReq) Descriptor() ([]byte, []int) {
	return file_audio_processing_proto_rawDescGZIP(), []int{0}
}

func (x *SpeechToTextReq) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *SpeechToTextReq) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SpeechToTextReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// 语音转文字响应
type SpeechToTextResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`               // 识别出的文字
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"` // 识别置信度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeechToTextResp) Reset() {
	*x = SpeechToTextResp{}
	mi := &file_audio_processing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeechToTextResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeechToTextResp) ProtoMessage() {}

func (x *SpeechToTextResp) ProtoReflect() protoreflect.Message {
	mi := &file_audio_processing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeechToTextResp.ProtoReflect.Descriptor instead.
func (*SpeechToTextResp) Descriptor() ([]byte, []int) {
	return file_audio_processing_proto_rawDescGZIP(), []int{1}
}

func (x *SpeechToTextResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SpeechToTextResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SpeechToTextResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SpeechToTextResp) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// 文字转语音请求
type TextToSpeechReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`         // 要转换的文字
	Voice         string                 `protobuf:"bytes,2,opt,name=voice,proto3" json:"voice,omitempty"`       // 语音类型，如 "female", "male"
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"` // 语言代码，如 "zh-CN", "en-US"
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`     // 语速，1.0为正常语速
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextToSpeechReq) Reset() {
	*x = TextToSpeechReq{}
	mi := &file_audio_processing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextToSpeechReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextToSpeechReq) ProtoMessage() {}

func (x *TextToSpeechReq) ProtoReflect() protoreflect.Message {
	mi := &file_audio_processing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextToSpeechReq.ProtoReflect.Descriptor instead.
func (*TextToSpeechReq) Descriptor() ([]byte, []int) {
	return file_audio_processing_proto_rawDescGZIP(), []int{2}
}

func (x *TextToSpeechReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextToSpeechReq) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *TextToSpeechReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TextToSpeechReq) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

// 文字转语音响应
type TextToSpeechResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,3,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"` // 生成的音频数据
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`                        // 音频格式，如 "wav", "mp3"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextToSpeechResp) Reset() {
	*x = TextToSpeechResp{}
	mi := &file_audio_processing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextToSpeechResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextToSpeechResp) ProtoMessage() {}

func (x *TextToSpeechResp) ProtoReflect() protoreflect.Message {
	mi := &file_audio_processing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextToSpeechResp.ProtoReflect.Descriptor instead.
func (*TextToSpeechResp) Descriptor() ([]byte, []int) {
	return file_audio_processing_proto_rawDescGZIP(), []int{3}
}

func (x *TextToSpeechResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TextToSpeechResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TextToSpeechResp) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *TextToSpeechResp) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_audio_processing_proto protoreflect.FileDescriptor

const file_audio_processing_proto_rawDesc = "" +
	"\n" +
	"\x16audio-processing.proto\x12\x0faudioprocessing\"d\n" +
	"\x0fSpeechToTextReq\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"p\n" +
	"\x10SpeechToTextResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\"m\n" +
	"\x0fTextToSpeechReq\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05voice\x18\x02 \x01(\tR\x05voice\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\"s\n" +
	"\x10TextToSpeechResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x03 \x01(\fR\taudioData\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format2\xc2\x01\n" +
	"\x16AudioProcessingService\x12S\n" +
	"\fSpeechToText\x12 .audioprocessing.SpeechToTextReq\x1a!.audioprocessing.SpeechToTextResp\x12S\n" +
	"\fTextToSpeech\x12 .audioprocessing.TextToSpeechReq\x1a!.audioprocessing.TextToSpeechRespB%Z#explorapal/app/audio-processing/rpcb\x06proto3"

var (
	file_audio_processing_proto_rawDescOnce sync.Once
	file_audio_processing_proto_rawDescData []byte
)

func file_audio_processing_proto_rawDescGZIP() []byte {
	file_audio_processing_proto_rawDescOnce.Do(func() {
		file_audio_processing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_processing_proto_rawDesc), len(file_audio_processing_proto_rawDesc)))
	})
	return file_audio_processing_proto_rawDescData
}

var file_audio_processing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_audio_processing_proto_goTypes = []any{
	(*SpeechToTextReq)(nil),  // 0: audioprocessing.SpeechToTextReq
	(*SpeechToTextResp)(nil), // 1: audioprocessing.SpeechToTextResp
	(*TextToSpeechReq)(nil),  // 2: audioprocessing.TextToSpeechReq
	(*TextToSpeechResp)(nil), // 3: audioprocessing.TextToSpeechResp
}
var file_audio_processing_proto_depIdxs = []int32{
	0, // 0: audioprocessing.AudioProcessingService.SpeechToText:input_type -> audioprocessing.SpeechToTextReq
	2, // 1: audioprocessing.AudioProcessingService.TextToSpeech:input_type -> audioprocessing.TextToSpeechReq
	1, // 2: audioprocessing.AudioProcessingService.SpeechToText:output_type -> audioprocessing.SpeechToTextResp
	3, // 3: audioprocessing.AudioProcessingService.TextToSpeech:output_type -> audioprocessing.TextToSpeechResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audio_processing_proto_init() }
func file_audio_processing_proto_init() {
	if File_audio_processing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_processing_proto_rawDesc), len(file_audio_processing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audio_processing_proto_goTypes,
		DependencyIndexes: file_audio_processing_proto_depIdxs,
		MessageInfos:      file_audio_processing_proto_msgTypes,
	}.Build()
	File_audio_processing_proto = out.File
	file_audio_processing_proto_goTypes = nil
	file_audio_processing_proto_depIdxs = nil
}
